### ISSUE TITLE
Bitte weitere XDS Metadaten in Profil aufnehmen

### ISSUE THREAD

**Issue by amerzwe** [hl7germany/basisprofil-de-r4#105]
Im Profil MHD werden neben Class und Type Code weitere XDS Metadaten verwendet, um den Typ und die Herkunft des Dokuments besser zu beschreiben.
Könntet Ihr daher bitte noch Links zu folgenden ValueSets hinzufügen?
AuthorRole, http://art-decor.org/fhir/3.0/ihede-/ValueSet/1.2.276.0.76.11.30--20180713131246
AuthorSpeciality http://art-decor.org/fhir/3.0/ihede-/ValueSet/1.2.276.0.76.11.31--20180713132208

Für Dokumente
ConfidentialityCode http://art-decor.org/fhir/3.0/ihede-/ValueSet/1.2.276.0.76.11.33--20180713132759
EventCodeList http://art-decor.org/fhir/3.0/ihede-/ValueSet/1.2.276.0.76.11.34--20180713132843
FormatCode http://art-decor.org/fhir/3.0/ihede-/ValueSet/1.2.276.0.76.11.35--20181214170712
HelathCareFacilityType http://art-decor.org/fhir/3.0/ihede-/ValueSet/1.2.276.0.76.11.36--20181001183306
PracticeSettingCode http://art-decor.org/fhir/3.0/ihede-/ValueSet/1.2.276.0.76.11.37--20190517134631

Für Folderr
CodeList http://art-decor.org/fhir/3.0/ihede-/ValueSet/1.2.276.0.76.11.40--20180713132721

Für SubmissionSets
ContentTypeCode http://art-decor.org/fhir/3.0/ihede-/ValueSet/1.2.276.0.76.11.39--20180713132816

Danke,

Angela.

**Comment by simoneOnFhir** [comment]
Machen wir.
Könntet ihr noch redirects für die Canoncials einrichten, so dass wenn jemand z.B. auf http://ihe-d.de/ValueSets/IHEXDSauthorRole klickt, dass man dann zur Spezifikation des ValueSets gelangt?

Die Verwendung dieser ValueSets ist nicht verpflichten, oder? Sie gilt als Empfehlung und wäre daher in FHIR als ein "preferred" Binding abzudecken, korrekt?

**Comment by simoneOnFhir** [comment]
Abstimmung im Interop-Forum 15.9.2020:
Die ValueSets sollten über eine automatische Synchronisation aus Art-Decor in Simplifier überführt werden.

Die Diskussion über die Binding-Strength und eine Aufstellung der Zusammenhänge VS -> XDS-Metadaten -> FHIR-Elemente wird in Zulip erarbeitet.

**Comment by simoneOnFhir** [comment]
Kai stimmt sich mit Patrick bezüglich der Berechtigungen ab, anschließend wir mit IHE-DE vereinbart, in welchem Umfang die VS/CS exportiert werden.
Bitte alle IHE-Terminologie-Ressourcen in terminologie/ihe ablegen.

**Comment by simoneOnFhir** [comment]
Thread: https://chat.fhir.org/#narrow/stream/179183-german-(d-a-ch)/topic/XDS.20Metadaten.20in.20FHIR

**Comment by kheitmann** [comment]
Mir ist nicht ganz klar ob stu3 oder r4?

**Comment by simoneOnFhir** [comment]
Wir brauchen die Sync nur für R4!

**Comment by amerzwe** [comment]
Danke,

Angela.

Von: Kai U. Heitmann <notifications@github.com>
Gesendet: Mittwoch, 16. September 2020 17:05
An: hl7germany/basisprofil-de-r4 <basisprofil-de-r4@noreply.github.com>
Cc: Merzweiler, Angela <Angela.Merzweiler@med.uni-heidelberg.de>; Author <author@noreply.github.com>
Betreff: Re: [hl7germany/basisprofil-de-r4] Bitte weitere XDS Metadaten in Profil aufnehmen (#105)


Ich habe diese ValueSets nun parasitiert und wenn der Zugang zum GitHub geregelt ist, können diese entsprechend synchronisiert werden

1.2.276.0.76.11.30--20180713131246



1.2.276.0.76.11.31--20180713132208



1.2.276.0.76.11.33--20180713132759



1.2.276.0.76.11.34--20180713132843



1.2.276.0.76.11.35--20181214170712



1.2.276.0.76.11.36--20181001183306



1.2.276.0.76.11.37--20190517134631



1.2.276.0.76.11.40--20180713132721



1.2.276.0.76.11.39--20180713132816

**Comment by amerzwe** [comment]
?Hi,

das sieht in den Mails sehr gut aus. Wo finde ich es im Implementation Guide?

Oder wartet Ihr noch auf etwas von uns?


Angela.

________________________________
Von: Merzweiler, Angela
Gesendet: Freitag, 18. September 2020 12:27
An: 'hl7germany/basisprofil-de-r4'; hl7germany/basisprofil-de-r4
Cc: Author
Betreff: AW: [hl7germany/basisprofil-de-r4] Bitte weitere XDS Metadaten in Profil aufnehmen (#105)

Danke,

Angela.

Von: Kai U. Heitmann <notifications@github.com>
Gesendet: Mittwoch, 16. September 2020 17:05
An: hl7germany/basisprofil-de-r4 <basisprofil-de-r4@noreply.github.com>
Cc: Merzweiler, Angela <Angela.Merzweiler@med.uni-heidelberg.de>; Author <author@noreply.github.com>
Betreff: Re: [hl7germany/basisprofil-de-r4] Bitte weitere XDS Metadaten in Profil aufnehmen (#105)


Ich habe diese ValueSets nun parasitiert und wenn der Zugang zum GitHub geregelt ist, können diese entsprechend synchronisiert werden

1.2.276.0.76.11.30--20180713131246



1.2.276.0.76.11.31--20180713132208



1.2.276.0.76.11.33--20180713132759



1.2.276.0.76.11.34--20180713132843



1.2.276.0.76.11.35--20181214170712



1.2.276.0.76.11.36--20181001183306



1.2.276.0.76.11.37--20190517134631



1.2.276.0.76.11.40--20180713132721



1.2.276.0.76.11.39--20180713132816



-

**Comment by patrick-werner** [comment]
adbot4git wurde hl7germany hinzugefügt und hat Schreibrechte in allen Repos.

Die Terminologien sollte der Bot bitte unter: https://github.com/hl7germany/basisprofil-de-r4/tree/master/terminologie/ihe ablegen.

**Comment by kheitmann** [comment]
Alles sollte seit einer Woche funktionieren. Könnt ihr das bestätigen?

**Comment by alexzautke** [comment]
@kheitmann Alle ValueSets wurden in Simplifier erfolgreich importiert. @amerzwe Bitte um kurze Bestätigung, dass das Issue geschlossen werden kann.

**Comment by patrick-werner** [comment]
Habe gerade den Import überprüft. Das VS: https://github.com/hl7germany/basisprofil-de-r4/blob/master/terminologie/ihe/ValueSet-1.2.276.0.76.11.36--20181001183306.xml included zwei weitere VS die nicht mit commited wurden.

Noch im Repo fehlend:
http://art-decor.org/fhir/ValueSet/1.2.276.0.76.11.58--20180713162142
http://art-decor.org/fhir/ValueSet/1.2.276.0.76.11.59--20180713162125

@kheitmann

**Comment by kheitmann** [comment]
Die beiden fehlenden Value Sets sind jetzt mit aufgenommen.

**Comment by patrick-werner** [comment]
Es fehlen noch die CodeSysteme zu den ValueSets, kann art-decor diese auch direkt übermitteln?

Ursprung der Anfrage:
https://chat.fhir.org/#narrow/stream/179183-german-(d-a-ch)/topic/CodeSystems.20f.C3.BCr.20IHE-ValueSets

**Comment by amerzwe** [comment]
ArtDecor verwaltet leider keine Codesysteme nur ValueSets.

Von: Patrick Werner <notifications@github.com>
Gesendet: Mittwoch, 25. November 2020 10:52
An: hl7germany/basisprofil-de-r4 <basisprofil-de-r4@noreply.github.com>
Cc: Merzweiler, Angela <Angela.Merzweiler@med.uni-heidelberg.de>; Mention <mention@noreply.github.com>
Betreff: Re: [hl7germany/basisprofil-de-r4] Bitte weitere XDS Metadaten in Profil aufnehmen (#105)


Es fehlen noch die CodeSysteme zu den ValueSets, kann art-decor diese auch direkt übermitteln?

Ursprung der Anfrage:
https://chat.fhir.org/#narrow/stream/179183-german-(d-a-ch)/topic/CodeSystems.20f.C3.BCr.20IHE-ValueSets

**Comment by simoneOnFhir** [comment]
Hallo zusammen,

ich vermisse aktuell noch die beiden VS mit den IHE XDS Document TypeCodes und den ClassCodes in den deutschen Basisprofilen.

...also die wichtigsten :D

**Comment by kheitmann** [comment]
Die sind mir ausdrücklich nicht genannt worden. @IHE sollte mir dazu die entsprechenden Identifier melden, hier also fehlten bisher 1.2.276.0.76.11.32 und 1.2.276.0.76.11.38. Absicht?

**Comment by amerzwe** [comment]
Die waren schon in dem Leitfaden erwähnt, deswegen hatte ich sie nicht noch einmal angegeben. Klar sollen die auch verwendet werden.

Von: Kai U. Heitmann <notifications@github.com>
Gesendet: Mittwoch, 9. Dezember 2020 14:42
An: hl7germany/basisprofil-de-r4 <basisprofil-de-r4@noreply.github.com>
Cc: Merzweiler, Angela <Angela.Merzweiler@med.uni-heidelberg.de>; Mention <mention@noreply.github.com>
Betreff: Re: [hl7germany/basisprofil-de-r4] Bitte weitere XDS Metadaten in Profil aufnehmen (#105)


Die sind mir ausdrücklich nicht genannt worden. @IHE<https://github.com/IHE> sollte mir dazu die entsprechenden Identifier melden, hier also fehlten bisher 1.2.276.0.76.11.32 und 1.2.276.0.76.11.38. Absicht?

**Comment by kheitmann** [comment]
Welche _Versionen_ konkret, Angela?
1.2.276.0.76.11.32 
1.2.276.0.76.11.38

**Comment by amerzwe** [comment]
Bei beiden Version 2. Wir werden demnächst aber auch die V3 zur Abstimmung bringen. Sobald die final ist, V3.

Von: Kai U. Heitmann <notifications@github.com>
Gesendet: Mittwoch, 9. Dezember 2020 18:11
An: hl7germany/basisprofil-de-r4 <basisprofil-de-r4@noreply.github.com>
Cc: Merzweiler, Angela <Angela.Merzweiler@med.uni-heidelberg.de>; Mention <mention@noreply.github.com>
Betreff: Re: [hl7germany/basisprofil-de-r4] Bitte weitere XDS Metadaten in Profil aufnehmen (#105)


Welche Versionen konkret, Angela?
1.2.276.0.76.11.32
1.2.276.0.76.11.38

**Comment by kheitmann** [comment]
Dann ist das jetzt erstmal erledigt von dieser Seite

**Comment by amerzwe** [comment]
Danke, super,

Angela

Von: Kai U. Heitmann <notifications@github.com>
Gesendet: Mittwoch, 9. Dezember 2020 18:23
An: hl7germany/basisprofil-de-r4 <basisprofil-de-r4@noreply.github.com>
Cc: Merzweiler, Angela <Angela.Merzweiler@med.uni-heidelberg.de>; Mention <mention@noreply.github.com>
Betreff: Re: [hl7germany/basisprofil-de-r4] Bitte weitere XDS Metadaten in Profil aufnehmen (#105)


Dann ist das jetzt erstmal erledigt von dieser Seite

**Comment by simoneOnFhir** [comment]
Wir hatten im IG nur auf das VS in ArtDecor verlinkt. Aber ich habe jetzt einen konkreten Fall, in dem ich an die ClassCode/TypeCodes binden möchte, daher wäre es schön, das ValueSet auch als FHIR Ressource am Wickel zu haben...

...wir wissen ja jetzt wie's geht :)

**Comment by alexzautke** [comment]
@amerzwe Kann dieses Ticket geschlossen werden oder besteht noch Änderungsbedarf?

**Comment by alexzautke** [comment]
Da kein weiterer Bedarf gemeldet wurde, wird das Issue geschlossen.

**Comment by jpwiedekopf** [comment]
@kheitmann @marryah : Wie in #190 von mir angemerkt sollten dringend auch noch die in den IHE ValueSets referenzierten CodeSystems bereitgestellt werden - zum Einen im Basisprofile, aber mMn auch in der v3-Version der IHE ValueSets. Script und Ressourcen sind in #190 verlinkt - freue mich auf Rückmeldung!
