### ISSUE TITLE
Issue while importing CodeSystem in FHIR Server

### ISSUE THREAD

**Issue by gjergjsheldija** [hl7germany/basisprofil-de-r4#108]
While importing some of the CodeSystems from https://simplifier.net/packages/de.basisprofil.r4/0.9.11 run into the following error : 
```
http://hl7.org/fhir/StructureDefinition/shareablecodesystem, Element 'CodeSystem.concept': minimum required = 1, but only found 0
```
the issue was with the meta tag.  As defined here https://www.hl7.org/fhir/resource.html#Meta > profile it should not be present for this particular case 
After removing it the import was successful.
Thank you

**Comment by gjergjsheldija** [comment]
Duplicate of #107

**Comment by marryah** [comment]
referes to #107
