### ISSUE TITLE
Address.country ISO-Binding

### ISSUE THREAD

**Issue by simoneOnFhir** [hl7germany/basisprofil-de-r4#11]
es gibt eine Standard-Extension, um Länder-Codierungen an Addressen anzufügen:https://chat.fhir.org/#narrow/stream/179166-implementers/topic/Coding.20an.20Address
Wäre evtl etwas eleganter, als ein ValueSet-Binding an country...

**Comment by alexzautke** [comment]
https://chat.fhir.org/#narrow/stream/224725-german.2Fcommitters/topic/Address.2Ecountry.20ISO-Binding

**Comment by simoneOnFhir** [comment]
zurückgezogen: https://hl7germany.sharepoint.com/:w:/r/sites/TCFHIR/_layouts/15/Doc.aspx?sourcedoc=%7B8790F5C6-642C-4B49-B38D-CE621034E059%7D&file=2022-10-27%20TC%20Protokoll.docx&action=default&mobileredirect=true
