### ISSUE TITLE
Source Tag bei allen Invarianten entfernen

### ISSUE THREAD

**Issue by simoneOnFhir** [hl7germany/basisprofil-de-r4#111]
Müssten eigentlich die canonicals rein, Forge setzt jedoch nur Datentypnamen.
So lange Forge das nicht korrekt macht, entfernen wir's
per TC Beschluss vom 14.9.2020

**Comment by alexzautke** [comment]
<source> wurde aus allen Profilen entfernt. Gleichzeitig wurde auch die durch Forge fälschlicherweise hinzugefügte normative-version Extension entfernt.
