### ISSUE TITLE
Schreibweise von Name-Elementen vereinheitlichen

### ISSUE THREAD

**Issue by simoneOnFhir** [hl7germany/basisprofil-de-r4#113]
z.B.:
extensions/Extension-destatis-ags.StructureDefinition.xml 
  <name value="Extension-destatis-ags" />
ändern in:   <name value="ExtensionDestatisAgs" />

extensions/Extension-seitenlokalisation.xml
  <name value="Extension-seitenlokalisation" />
 ändern in:   <name value="ExtensionSeitenlokalisation" />

ressourcen-profile/Namingsystem-de-basis.StructureDefinition.xml
  <name value="namingsystem-de-basis" />
ändern in:    <name value="NamingSystemDeBasis" />

**Comment by alexzautke** [comment]
Alle Namen aller Ressourcen wurden nun harmonisiert.
