### ISSUE TITLE
Profil address-de-basis: Constraint add-7 ist problematisch

### ISSUE THREAD

**Issue by lhitc** [hl7germany/basisprofil-de-r4#119]
Die precinct-Extension hängt direkt an Address, nicht an line.
Dennoch wird in add-7 gefordert, dass eine Line mit dem Ortsteil existiert. Ist dies beabsichtigt?
Zumindest ist es nicht intuitiv.

**Comment by alexzautke** [comment]
Die Dokumentation hierzu ist im IG angepasst. Siehe https://simplifier.net/guide/basisprofil-de-r4/Patient#Patient.address.
