### ISSUE TITLE
Fehler im IG: File missing. ICD-10.md was not found in the project.

### ISSUE THREAD

**Issue by simoneOnFhir** [hl7germany/basisprofil-de-r4#122]
Siehe: https://simplifier.net/guide/basisprofil-de-r4/Condition#ICD-10-GMProfil

**Comment by simoneOnFhir** [comment]
Betrifft mehrere Dateien ( auch Beispiele) unter dem Kapitel ICD-10-GM

**Comment by alexzautke** [comment]
ICD-10 Kapitel ist nun korrigiert.
