### ISSUE TITLE
Profile-coverage-de-gkv verweist auf nicht existentes Profil http://fhir.de/StructureDefinition/organization-de-basis

### ISSUE THREAD

**Issue by patrick-werner** [hl7germany/basisprofil-de-r4#126]
https://github.com/hl7germany/basisprofil-de-r4/blob/5a4a14678d42d5f2e22ad6ee40a6a2404e7421eb/ressourcen-profile/Profile-coverage-de-gkv.xml#L278

Profile-coverage-de-gkv verweist auf nicht existentes Profil http://fhir.de/StructureDefinition/organization-de-basis

In https://chat.fhir.org/#narrow/stream/224725-german.2Fcommitters/topic/organization-basis.20fehlt.20in.20R4 wurde besprochen dieses auch nicht in R4 zu erstellen, aber spezifische Profile bspw. für GKV Kostenträger zu erstellen.

**Comment by alexzautke** [comment]
Fixed in 0.9.13
