### ISSUE TITLE
Migration http://fhir.de/StructureDefinition/gender-amtlich-de auf http://hl7.org/fhir/StructureDefinition/patient-genderIdentity

### ISSUE THREAD

**Issue by abiernat-cerner** [hl7germany/basisprofil-de-r4#128]
HL7 International hat in FHIR inzwischen die Extension http://hl7.org/fhir/StructureDefinition/patient-genderIdentity vorgesehen. Soweit ich das Überblicke haben wir hier zwei Extension mit derselben Zweckbestimmung. Ich möchte vorschlagen mittelfristig auf die Extension http://hl7.org/fhir/StructureDefinition/patient-genderIdentity zu migrieren. Das Terminiologiebinding ist noch anzupassen.
Vorteil, ist dass wir dann die Patienten besser grenzüberschreitend austauschen können.

**Comment by alexzautke** [comment]
Dieses Ticket wurde während des letzten Interoperabilitätsforums diskutiert. Die gender-amtlich-de Extension verfolgt einen anderen Scope. Hier geht es zunächst nur um die Abbildung der Option "divers" in Anlehnung an das Personenstandsgesetz im Kontext der Erfassung eines Administrativen Geschlechts. Divers muss in Patient.gender (oder allen erlaubten Kontexten) anders wie "other" abgebildet werden, da dies zwei semantisch unterschiedliche Aussagen sind. Die patient-genderIdentity Extension kann * *zusätzlich** verwendet werden, um die persönliche Präferenz zur Ausdifferenzierung der Option "Divers" zu erfassen.
