### ISSUE TITLE
Beispiele in GitHub überführen

### ISSUE THREAD

**Issue by simoneOnFhir** [hl7germany/basisprofil-de-r4#13]
Einige der Beispiele sind nur auf Simplifier.
Müssen nach Git überführt werden, jedoch so, dass hinterher beim Sync keine Duplikate auf Simplifier entstehen und die Verweise im IG intakt bleiben :-/

**Comment by alexzautke** [comment]
Alle Beispiel wurden in GitHub überführt, validiert, korrigiert und beschriftet.
