### ISSUE TITLE
Terminology Dependencies zu KBV Projekten klären

### ISSUE THREAD

**Issue by patrick-werner** [hl7germany/basisprofil-de-r4#133]
Die Basisprofile verwenden durch die KBV definierte CS&VS, bspw.: https://fhir.kbv.de/ValueSet/74_VS_AW_EBM     
Um gegen die Basisprofile validieren zu können benötigen wir diese CS&VS im ValidationScope.

Da viele KBV Projekte von den basisprofilen erben ist eine dependency zu existenten KBV packages problematisch (VOS enthält momentan das EBM VS).

Diskutierte Lösung:
Die KBV erstellen eine dependency freies Projekt: KBV Terminologie in welchen die CS&VS welche durch die KBV definiert werden enthalten sind. Zu diesem package kann dann eine dependency von basis-r4 hinzugefügt werden.

**Comment by alexzautke** [comment]
Duplikat: https://hl7germany.atlassian.net/browse/HFB-29
