### ISSUE TITLE
CodeSystem has an 'all system' value set of but it is an expansion

### ISSUE THREAD

**Issue by patrick-werner** [hl7germany/basisprofil-de-r4#135]
Aktuell erzeugt der Java Validator folgenden Error auf einigen CS:

```
*FAILURE*: 1 errors, 0 warnings, 0 notes
  Error @ CodeSystem : CodeSystem http://fhir.de/CodeSystem/gender-amtlich-de has an 'all system' value set of http://fhir.de/ValueSet/gender-amtlich-de, but it is an expansion
```

In Conformance angefragt, sollte erlaubt sein:
https://chat.fhir.org/#narrow/stream/179177-conformance/topic/but.20it.20is.20an.20expansion

**Comment by alexzautke** [comment]
@patrick-werner Kann das Issue geschlossen werden?

**Comment by alexzautke** [comment]
Fehler ist nicht mehr in der aktuellen Version des Java Validator vorhanden (5.2.20).
