### ISSUE TITLE
Canonical URLs must be absolute URLs

### ISSUE THREAD

**Issue by patrick-werner** [hl7germany/basisprofil-de-r4#136]
Validator Bug, Zulip thread:
https://chat.fhir.org/#narrow/stream/179177-conformance/topic/java.20validator.3A.20Canonical.20URLs.20must.20be.20absolute.20URLs
```
*FAILURE*: 1 errors, 0 warnings, 0 notes
  Error @ CodeSystem.supplements (line 24, col40) : Canonical URLs must be absolute URLs if they are not fragment references (urn:iso:std:iso:3166)
```

**Comment by alexzautke** [comment]
@patrick-werner Ist das jetzt gefixt und kann geschlossen werden?

**Comment by alexzautke** [comment]
Fehler ist nicht mehr in der aktuellen Version des Java Validator vorhanden (5.2.20).
