### ISSUE TITLE
KBV-Terminologien abklären

### ISSUE THREAD

**Issue by simoneOnFhir** [hl7germany/basisprofil-de-r4#14]
Wir verwenden nach wir vor fhir.de-URLs für 

http://fhir.de/ValueSet/kbv/ebm
http://fhir.de/ValueSet/kbv/s-icd-diagnosesicherheit
http://fhir.de/ValueSet/kbv/s-icd-seitenlokalisation

da diese von der KBV noch nicht publiziert sind.

Bitte klären, ob wir das so lassen sollen, oder welche URLs hier künftig zu verwenden sind...

**Comment by lhitc** [comment]
Zwischenzeitlich erledigt.

**Comment by alexzautke** [comment]
Für alle KBV NamingSystems / CodeSysteme ist nun im IG dokumentiert, dass die entsprechenden Verweise nicht Teil der Deutschen Basisprofile sind.
