### ISSUE TITLE
Basisprofile enthalten Abhängigkeiten auf KBV Terminologie in KBV Basis

### ISSUE THREAD

**Issue by patrick-werner** [hl7germany/basisprofil-de-r4#143]
Dies führt zu einer zirkulären Abhängigkeit.
Mögliche Lösung: Die KBV extrahiert Terminologien aus dem KBV Basis Paket.

Dependencies dann: KBV.Terminologie <- basisprofile.r4 <- KBV.Basis

Betroffene VS:

- https://fhir.kbv.de/ValueSet/KBV_VS_SFHIR_KBV_NORMGROESSE
- https://fhir.kbv.de/ValueSet/KBV_VS_SFHIR_KBV_DMP
- https://fhir.kbv.de/ValueSet/KBV_VS_SFHIR_ITA_WOP
- https://fhir.kbv.de/ValueSet/KBV_VS_SFHIR_ICD_SEITENLOKALISATION
- https://fhir.kbv.de/ValueSet/KBV_VS_SFHIR_KBV_VERSICHERTENSTATU
- https://fhir.kbv.de/ValueSet/KBV_VS_SFHIR_KBV_PERSONENGRUPPE
-  https://fhir.kbv.de/ValueSet/74_VS_AW_EBM

edit: gilt natürlich ebenfalls für die zugrunde liegenden CS.

**Comment by alexzautke** [comment]
Siehe https://hl7germany.atlassian.net/browse/HFB-29
