### ISSUE TITLE
Hinweise auf Device-Profile hinzufügen

### ISSUE THREAD

**Issue by simoneOnFhir** [hl7germany/basisprofil-de-r4#15]
https://simplifier.net/IEEE11073-10207IG/~introduction

(Dräger, Philipps)

**Comment by simoneOnFhir** [comment]
Wird im Februar ballotiert....

**Comment by alexzautke** [comment]
Verweis auf http://build.fhir.org/ig/HL7/uv-pocd/ wurde hinzugefügt. Es erfolgte keine Ballotierung des oben genannten IGs, deshalb wird kein Verweis in die Basisprofile aufgenommen.
