### ISSUE TITLE
FHIR Core Spec verweist für ICD-10-GM auf HL7-D-OID-Seite

### ISSUE THREAD

**Issue by lhitc** [hl7germany/basisprofil-de-r4#191]
Unter http://www.hl7.org/fhir/icd.html wird für die Repräsentation von ICD-10-GM auf 
http://wiki.hl7.de/index.php?title=Kodesysteme verwiesen.
Diese Wiki-Seite benennt die OIDs, aber nicht das FHIR CodeSystem / canonical URL.

Auf dieser Wiki-Seite sollte daher ein Link auf die passende Seite des FHIR Basisprofil-IG gesetzt werden.

(TC FHIR 2021-03-15)

**Comment by alexzautke** [comment]
Siehe https://hl7germany.atlassian.net/browse/HFB-39
