### ISSUE TITLE
https in Canonicals verwenden

### ISSUE THREAD

**Issue by alexzautke** [hl7germany/basisprofil-de-r4#198]
Kommentar eingereicht durch: Axel Biernat / Cerner Health Services Deutschland GmbH
Kategorie: Ablehnende Kritik
Bezug im Dokument: "Grundlagen / Nomenklatur"

Existierende Formulierung: "URLs der Form http://fhir.de/<Ressourcen-Typ>/<Name des Profils>-de-basis"
Änderungsvorschlag: "https://…."
Kommentar / Begründung: "Auch wenn es sich nur um Canonical URLs handelt, so sollen diese auch auflösbar sein. Die Nutzung des http Protokolls ist veraltet und es sollte auf https umgestellt werden"

**Comment by simoneOnFhir** [comment]
Canonicals sond per Definition "a special kind of Business identifier" und daher unabhängig vom zugrunde liegenden Protokoll.

Die Auflösung einer Canonical zur MasterDefinition erfolgt ohnehin mittels eines redirects (in unserem Fall auf "https://simplifier.net/resolve=<canonical>"

Die Abfrage bspw eines Profile von einem Server erfolgt mittels https://<endpoint>/StructureDefinition?url=<canonical>

Die Canonical hat also in keinem Fall eine Auswirkung auf das tatsächlich verwendete Protokoll für die Übertragung der Ressource.

Die Änderung der Canonicals hätte weitereichende Folgen (Breaking Change für *alle* Artefakte), jedoch keine nennenswerte Vorteile. Insbesondere so lange die Canonicals der FHIR-Spezifikation selbst weiterhin http verwenden.

Pläme, dies zu ändern gibt es nicht.

Siehe auch: https://chat.fhir.org/#narrow/stream/179202-terminology/topic/URI.20protocol
