### ISSUE TITLE
Verwendung IHE-MHD-Profil

### ISSUE THREAD

**Issue by alexzautke** [hl7germany/basisprofil-de-r4#208]
Kommentar eingereicht durch: "Axel Biernat / Cerner Health Services Deutschland GmbH"
Kategorie: Ablehnende Kritik
Bezug im Dokument: Ressourcen / Dokumente (DocumentReference) 

Existierende Formulierung: "Für den (einrichtungsübergreifenden) Dokumentenaustausch eigent sich das IHE-MHD-Profil, das die Akteure Document-Source, Document-Recipient, Document-Provider und Document-Consumer beschreibt."
Kommentar / Begründung: "Hier erfolgt eine Vereinfachung, die Grundprinzipien von IHE Profilen ausser Acht lässt. Hier findet sich nur die Datenstruktur und Terminologie, in IHE auch das Verhalten. Es ist gut den Verweis auf das MHD aufzunehmen, aber der Abschnitt ist zu erweitern."

**Comment by alexzautke** [comment]
https://chat.fhir.org/#narrow/stream/179183-german-.28d-a-ch.29

**Comment by alexzautke** [comment]
IHE Grundprinzipien oder sonst allgemeine Erläuterungen werden nicht in die Basisprofile aufgenommen. Verweis auf IHE Technical Frameworks General Introduction and Shared Appendices wurde eingefügt. Absatz zu MHD wurde erweitert.

**Comment by simoneOnFhir** [comment]
Wird im Modul ISiK - Dokumentenaustausch spezifiziert. Basis-De kann darauf referenzieren.
