### ISSUE TITLE
0..0 Constraints in Versicherungs-Informationen (Coverage)

### ISSUE THREAD

**Issue by alexzautke** [hl7germany/basisprofil-de-r4#212]
Kommentar eingereicht durch: Axel Biernat / Cerner Health Services Deutschland GmbH
Kategorie: Ablehnende Kritik
Bezug im Dokument: Ressourcen / Versicherungs-Informationen (Coverage)

Existierende Formulierung: "Null Constraining im Basisprofil http://fhir.de/StructureDefinition/coverage-de-basis"
Kommentar / Begründung: "Auch wenn es heute keine Verwendung des Elements gibts, so empfiehlt sich in einem Basisprofil nicht das Null-Constrainen. Es wäre besser dies ausschließlich über Kommentar zu addressieren. Falls wir einen Use Case identizifieren, wäre ein neues Major Release erforderlich."

**Comment by simoneOnFhir** [comment]
Die Constraints wurden bewusst so gewählt, weil die entsprechenden Angaben im Kontext des jeweiligen Profils keinen Sinn ergeben. Um eine Fehlinterpretation der Attribute zu verhindern, bzw. einen fehlerhaften Gebrauch der Profile vorzubeugen, wurden die Felder bewusst "verboten".
Beispiel: Man könnte den Hauptversicherten sowohl als "subscriber" als auch als "policyHolder" auffassen. Da im Kontext der gesetzlichen Versicherung jedoch der "subscriber" besser passt, wurde "policyHolder" auf 0..0 constraint, um die Ambiguität zu minimieren.
Eine Lockerung der Constraints zeihen wir nur in Betracht, sofern ein konkreter Use Case identifiziert werden kann, in der eines der constrainten Felder explizit benötigt wird.
