### ISSUE TITLE
Kodierung Plegestufen

### ISSUE THREAD

**Issue by alexzautke** [hl7germany/basisprofil-de-r4#217]
Kommentar eingereicht durch: "Axel Biernat / Cerner Health Services Deutschland GmbH"
Kategorie: Rückfrage
Bezug im Dokument: Resourcen / Beobachtungen, Messungen (Observation)

Kommentar / Begründung: "Werden Pflegestufen mit OPS klassifiziert? Mir ist diese Nutzung in der Praxis so noch nicht begeht. Können wir dies bitte durch einen Pflege-SME bestätigen lassen."

**Comment by alexzautke** [comment]
@marryah Könntest du hierzu ein paar Background-Infos im Chat liefern?

**Comment by marryah** [comment]
Das valueset habe ich aus einem CDA-Projekt. Ich meine, dass @julsas da noch mehr Infos hat...

**Comment by julsas** [comment]
> "Werden Pflegestufen mit OPS klassifiziert?" 

Offensichtlicht ja, wenn der OPS dafür Codes definiert hat.

> Nutzung in der Praxis

Da OPS, wenn wahrscheinlich nur im Krankenhaus Kontext. Der CDA Use Case war ambulante Intensivpflege und damit sozusagen Off-Label-Use der OPS Codes. Aber sollte ja nicht verboten sein, die Definitionen außerhalb von DRG etc. zu verwenden. Alternative wäre ein eigenes CodeSystem gewesen. Vielleicht aber nochmal einen Pflege-SME fragen, der mehr auf dem Laufenden ist in dem Bereich @marryah

**Comment by mmreith** [comment]
Hey Zusammen, @alexzautke @julsas @marryah 

das war ein Kommentar von uns: Nämlich dass bei solchen Sachen gleich an mehrere slices gedacht werden sollte, denn wir benötigen nach unseren Projektstatuten eine Snomed-Codierung an dieser Stelle. Dann wäre die Sache auch generell offen und man könnte beliebige eigene VS/CS hinzufügen.

**Comment by julsas** [comment]
Guter Use Case für die DE National Extension von SNOMED gleich mal die Pflegegrade aufzunehmen. Die Möglichkeit hatten wir damals nicht.

**Comment by alexzautke** [comment]
@mmreith Stimme ich vollkommen zu. Die Observation-Profile passen wir noch an. Frage wäre was hier das primäre Codesystem ist, dass wir verpflichtend machen? OPS weil wir Codes dafür schon haben + optional SNOMED?

@julsas @patrick-werner @marryah Wer könnte sich um die Beantragung der Codes kümmern?

**Comment by julsas** [comment]
> Wer könnte sich um die Beantragung der Codes kümmern?

Kann ich machen

**Comment by mmreith** [comment]
Ich frage mal kurz beim Pflege-MIO nach, ob da schon was gemacht wurde...

**Comment by mmreith** [comment]
Die Codes wurden schon beantragt. 
Nach dem Pflege-Team sind die Codes wie sie derzeit vorhanden sind soweit okay und da die Erstellung von neuen Snomed-Codes sicherlich sehr lange dauern wird, sollten wir die OPS verpflichtend machen und snomed optional

**Comment by marryah** [comment]
Hallo @mmreith @julsas @alexzautke: Kurze Frage: Wollen wir diese Diskussion kurz zusammengefasst in den zulip-Chat stellen? Dann ist die Community informiert.
