### ISSUE TITLE
Erweiterung other-amtlich

### ISSUE THREAD

**Issue by alexzautke** [hl7germany/basisprofil-de-r4#221]
Kommentar eingereicht durch: Axel Biernat / Cerner Health Services Deutschland GmbH
Kategorie: Vorschlag
Bezug im Dokument: Extensions / Geschlecht

Änderungsvorschlag: "Aufnahme der anderen Geschlechter (männlich|weiblich|unbekannt) in das Valueset."
Kommentar / Begründung: "Für den Konsumenten der Instanz, ist es einfacher für die Weiterverarbeitung die Geschlechtsinformation von einer Stelle zu lesen, als über eine Businesslogik zwei Elemente auszuwerten.
Im Sinne des Personenstandsgesetz, welches die Grundlage für das Valueset darstellt, aber vermittelbar. Hier sind die vergenannten Ausprägungen aus benannt."

**Comment by simoneOnFhir** [comment]
Es ist davon auszugehen, dass in der überwiegenden Anzahl der Weiterverarbeitungsprozesse (Anrede des Patienten, Bettenzuweiseung etc) die Information "other" und damit das Auslesen von Patient.gender ausreichend ist. Die Differenzierung in divers/unbestimmt wird in den wenigsten Fällen benötigt und in noch weniger Fällen für die Businesslogik ausschlaggebend sein.  Wir möchten nicht 100% der Systeme zur Verwendung einer Extension zwingen, die nur in Ausnahmefällen tatsächlich benötigt wird.

**Comment by alexzautke** [comment]
Invariante wird hinzugefügt als Vorschlag für MI-I, gematik und KBV und als Hinweis in den IG: gender = 'other' implies gender.extension('<canonical>').exists()
