### ISSUE TITLE
MR als Identifier.type für PID

### ISSUE THREAD

**Issue by alexzautke** [hl7germany/basisprofil-de-r4#226]
Kommentar eingereicht durch: Axel Biernat / Cerner Health Services Deutschland GmbH
Kategorie: Ablehnende Kritik
Bezug im Dokument: Datentypen / Identifier / Organisationsinterner Patienten-Identifier (PID)

Existierende Formulierung: "Da es beim organisationsinternen Identifier keinen einheitlichen Namensraum gibt, ist hier die Angabe des type-Codes "MR" (Medical Record Number) verpflichtend, um die PID einrichtungsübergreifend als solche erkennen zu können."
Änderungsvorschlag: "Verwendung von "PI""
Kommentar / Begründung: "In der genannten Terminologie https://terminology.hl7.org/2.1.0/CodeSystem-v2-0203.html wird das Konzept MR vorgeschlagen. Dieses ist für den Medical Record vorgesehen. Dies entspricht der Krankenakte. Siehe auch die Übersetzung. Die Krankenakte ist nicht ident zur internen Patientnummer. Stattdessen sollte PI mit der Übersetzung "interne Patienten-ID" verwendet werden."

**Comment by simoneOnFhir** [comment]
"PI" ist nicht Bestandteil der in FHIR für Identifier.type vorgesehenen ValueSets: 
https://hl7.org/fhir/valueset-identifier-type.html

**Comment by simoneOnFhir** [comment]
Die Verwendung des Type-Codes "MR" für Einrichtungsinterne Patienten-IDs ist in FHIR bereits gängige Praxis, siehe 
https://hl7.org/fhir/R4/patient-examples.html

**Comment by alexzautke** [comment]
Durch das TC FHIR wurde eine Anfrage an die HL7 Int. PA Working Group gestellt. Es wird eine Anfrage an UTG gestellt in welchem Fall MR oder PI zu verwenden ist. Eins der beiden Konzepte sollte ansonsten zurückgezogen werden. International ist "MR" häufiger verwendet und wird als Empfehlung von PA herausgegeben: https://confluence.hl7.org/display/PA/Using+FHIR+Identifiers
