### ISSUE TITLE
Identifier-Profil für die Abbildung einer Patienten-ID hat falsche URL

### ISSUE THREAD

**Issue by mmreith** [hl7germany/basisprofil-de-r4#23]
Identifier-Profil für die Abbildung einer Patienten-ID hat die URL

http://fhir.de/StructureDefinition/identifier-**kvid-10**

**Comment by simoneOnFhir** [comment]
Wo genau tritt das Problem auf? Ich find's nicht...

**Comment by mmreith** [comment]
Hmm ich auch nicht mehr...Vielleicht hat Simplifier das falsch angezeigt, denn in der Vorgängerversion war es in der Tat falsch...

Sorry

**Comment by simoneOnFhir** [comment]
Das kann gut sein... Danke fürs melden! Fehler finden wir immer am liebsten **vor ** dem Ballot :)
Wir freuen uns über jeden, der Hilft, die Basisprofile zu verbessern...
