### ISSUE TITLE
Kodierung .system in Reisepassnummer

### ISSUE THREAD

**Issue by alexzautke** [hl7germany/basisprofil-de-r4#233]
Kommentar eingereicht durch: Axel Biernat / Cerner Health Services Deutschland GmbH
Kategorie: Ablehnende Kritik
Bezug im Dokument: Datentypen / Identifier / Reisepassnummer

Existierende Formulierung: "<system value="http://hl7.org/fhir/sid/passport-DEU" />"
Kommentar / Begründung: "Ein Pass wird durch ein Land herausgeben und die Passnummer kann immer nur in Verbindung mit dem Ausstellenden Land interpretiert werden. Das Land als Aussteller ist nicht im Identifier-Profil benannt."

**Comment by simoneOnFhir** [comment]
Im Text sollte darauf verwiesen werden, dass die System-URL landesspezifisch ist.
