### ISSUE TITLE
meta tag: language auf deutsch für alle resources

### ISSUE THREAD

**Issue by patrick-werner** [hl7germany/basisprofil-de-r4#24]

**Comment by simoneOnFhir** [comment]
Diskussion hier: https://chat.fhir.org/#narrow/stream/179183-german-(d-a-ch)/topic/.5BBASIS.5D.20Issue.2324.3A.20language.20.3D.22DE.22.20f.C3.BCr.20Basisprofile

**Comment by patrick-werner** [comment]
nach Diskussion im TC FHIR wurde der Issue zurückgezogen.
