### ISSUE TITLE
Supplement identifier-type-v2

### ISSUE THREAD

**Issue by alexzautke** [hl7germany/basisprofil-de-r4#242]
Kommentar eingereicht durch: Axel Biernat / Cerner Health Services Deutschland GmbH
Kategorie: Ablehnende Kritik
Bezug im Dokument: Terminologie / Übersetzungen / identifier-type-v2

Existierende Formulierung: "MR Patientennummer?"
Kommentar / Begründung: "Siehe hierzu bereits oben."

**Comment by simoneOnFhir** [comment]
Evtl anpassen in "Einrichtungsinterne Patienten(-Akten-)Nummer" ?
