### ISSUE TITLE
ValueSet http://fhir.de/ValueSet/diagnosekategorie muss definiert werden

### ISSUE THREAD

**Issue by lhitc** [hl7germany/basisprofil-de-r4#25]
http://fhir.de/ValueSet/diagnosekategorie wird in condition-de-basis.category verwendet.
Ebenfalls das zugrundeliegende CodeSystem definieren (http://fhir.de/CodeSystem/diagnosekategorie).

Erfolgt durch TC Terminologie.

**Comment by simoneOnFhir** [comment]
...weiter in #18
