### ISSUE TITLE
Identifier.use Gesetzliche Krankenversichertennummer (10-stellige KVID)

### ISSUE THREAD

**Issue by alexzautke** [hl7germany/basisprofil-de-r4#251]
Kommentar eingereicht durch: Udo Siefker, Bettina Lieske, SAP SE
Kategorie: Ablehnende Kritik
Bezug im Dokument: Gesetzliche Krankenversichertennummer (10-stellige KVID)
https://ig.fhir.de/basisprofile-de/stable/Datentypen-Identifier.html

Änderungsvorschlag: "Stattdessen "secondary" verwenden für identifier.use im Patienten"
Kommentar / Begründung: "Die 10-stellige KVID ist weder lebenslang noch wird sie eindeutig vergeben. Deshalb ist der use "official" inkorrekt.
"official" hat unserem verständis nichts mit offiziell zu tun und ist deshalb missverständlich"

**Comment by simoneOnFhir** [comment]
Wir entfernen den fixed value auf Identifier.use und stellen es den Implementierungen damit frei, dieses Feld gemäß der eigenen Bedüfnisse zu verwenden. 
Wir weisen jedoch ausdrücklich darauf hin, dass es aufgrund der subjektiven Natur von Identifier.use nicht zu empfehlen ist, dem Feld in der Implementierung von Server-Server-Kommunikationen eine besondere Bedeutung zuzuweisen. Es sollte lediglich dazu verwendet werden, im Falle mehrerer vorhandener Identifier zu entscheiden, welche davon präferiert zur Anzeige gebracht werden soll.
Siehe http://hl7.org/fhir/managing.html#distributed
