### ISSUE TITLE
Address.line Kardinalität

### ISSUE THREAD

**Issue by alexzautke** [hl7germany/basisprofil-de-r4#252]
Kommentar eingereicht durch: Udo Siefker, Bettina Lieske, SAP SE
Kategorie: Vorschlag
Bezug im Dokument: Line bei address
https://ig.fhir.de/basisprofile-de/stable/Ressourcen-Patient.html#Ressourcen-Patient-Addresse

Existierende Formulierung: "line ist auf Kardinalität 0..3 beschränkt. Dies könnte in manchen Fällen nicht ausreichend"
Änderungsvorschlag: "Kardinalität nicht beschränken"
Kommentar / Begründung: "Beispiele: Wohnungsnummer, Stockwerk, z.Hdn. Von, Gebäudenummer"

**Comment by alexzautke** [comment]
Dokumentation für die einzelen Adressbestandteile wurde hinzugefügt

**Comment by simoneOnFhir** [comment]
Die Beschränkung wurde nach ausführlicher Recherche und Konsultation mit den geltenden DIN-Standards für Adressen eingeführt, (siehe https://simplifier.net/guide/basisprofil-de-r4/Ressourcen-Patient#Ressourcen-Patient-Addresse) um die Implementierung (insbesondere das Bedrucken von Kuverts und Etiketten zu erleichtern. 
Die Lines sind in der Länge nicht begrenzt, so dass es möglich sein sollte, alle erforderlichen Zustellhinweise unterzubringen. Die meisten Systeme sind nicht in der Lage mehr als drei Adresszeilen abzubilden (siehe z.B. Online-Frankierung der Post).

Siehe auch https://de.wikipedia.org/wiki/DIN_5008 
"Das EDV-gerechte Anschriftenfeld ist 9-zeilig nach internationaler Normung aufgebaut: 3 Zeilen für die Zusatz- und Vermerkzone (ZVZ), 6 Zeilen für die Anschriftzone (AZ).
3. ZVZ – z. B. elektronische Freimachungsvermerke
2. ZVZ – z. B. Vorausverfügung Nicht nachsenden!
1. ZVZ – z. B. Einschreiben / Recommandé
1. AZ – Firma (= Name des Unternehmens)
2. AZ – Anrede, ggf. Berufs- oder Amtsbezeichnungen
3. AZ – ggf. akademische Grade (z. B. Dr., Dipl.-Ing., Dipl.-Hdl.), Name
4. AZ – Straße/Hausnummer (ggf. // App.-Nr.) oder Postfach
5. AZ – Postleitzahl und Bestimmungsort
6. AZ – (LAND)"

Die Beschränkung erfolgte im Einvernehmen mit KBV, MI-I und Gematik
