### ISSUE TITLE
Required Binding Coverage.type

### ISSUE THREAD

**Issue by alexzautke** [hl7germany/basisprofil-de-r4#253]
Kommentar eingereicht durch: Udo Siefker, Bettina Lieske, SAP SE
Kategorie: Vorschlag
Bezug im Dokument: coverage.type
https://ig.fhir.de/basisprofile-de/stable/Ressourcen-VersicherungsInformationenCoverage.html

Existierende Formulierung: "Derzeit ist das valueSet binding required."
Änderungsvorschlag: "Wie in unserem Kommentar #7 beschrieben, sehen wir weiterere Versicherungsarten. Deshab würden wir hier kein required Binding vorsehen, sondern eher preferred oder extensible"

**Comment by simoneOnFhir** [comment]
Unser Ziel ist es, zunächst eine standardisierte Grob-Typisierung der Coverage vorzunehmen, soweit diese erforderlich ist zur Steuerung von Versorgungsprozessen (z.B. zur Klärung von Kostenübernahmen, abgedeckten Leistungen o.ä.).
Wenn darüber hinaus eine weitere Differenzierung in anderen Kontexten (z.B. Abrechnungssteuerung) erforderlich ist, sollte diese mit Hilfe von Extensions erfolgen, um dabei nicht die Allgemeinverständlichkeit des Versicherungsstatus eines Patienten einzuschränken.
