### ISSUE TITLE
Benennung Ambulanter/stationärer Fall / Kontakt (Encounter)

### ISSUE THREAD

**Issue by alexzautke** [hl7germany/basisprofil-de-r4#256]
Kommentar eingereicht durch: Udo Siefker, Bettina Lieske, SAP SE
Kategorie: Ablehnende Kritik
Bezug im Dokument: Encounter
https://ig.fhir.de/basisprofile-de/stable/Ressourcen-AmbulanterstationrerFallKontaktEncounter.html

Existierende Formulierung: "Ambulanter/stationärer Fall / Kontakt (Encounter)"
Änderungsvorschlag: "Ambulanter/stationärer Kontakt (Encounter)"
Kommentar / Begründung: "Der Begriff "Fall" sollte hier nicht verwendet werden, da, wie in den Erläuterungen zu lesen, dieser in FHIR dem Account zugeordnet ist."

**Comment by simoneOnFhir** [comment]
Der Begriff "Fall" in der Überschrift dient der Verbesserung der Auffindbarkeit der Informationen.
Der "Fall" ist ein bei weitem häufiger gebräuchlicher Begriff als "Kontakt".
Wir möchten insbesonderen den Lesern, die auf der Suche nach Informationen zur Abbildung eines Falles auf diese Seite lenken, wo die Differenzierung dargestellt wird. 

Die Überschrift wird zur Vermeidung von Fehlinterpretationen angepasst in  "Ambulanter/stationärer Fall / Kontakt (Encounter,Account,EpisodeOfCare)"
