### ISSUE TITLE
Umbenennung Aufnahmeart

### ISSUE THREAD

**Issue by alexzautke** [hl7germany/basisprofil-de-r4#257]
Kommentar eingereicht durch: Udo Siefker, Bettina Lieske, SAP SE
Kategorie: Ablehnende Kritik
Bezug im Dokument: Aufnahmeart
http://fhir.de/CodeSystem/dkgev/Aufnahmeart

Existierende Formulierung: "Hier handelt es sich um Abrechnungsarten und nicht um Aufnahmearten.
Weiterhin wird nur das codeSystem in den Basisprofilen definiert, aber es ist unklar, von welchem Element es als ValueSet verwendet werden soll."
Kommentar / Begründung: "In der vorherigen Ballot-Version stand noch „Zur Codierung der Aufnahmeart kann das folgende CodeSystem an Account.type gebunden werden:“ dies wäre aus unserer Sicht korrekt."

**Comment by alexzautke** [comment]
https://chat.fhir.org/#narrow/stream/224725-german.2Fcommitters/topic/Umbenennung.20Aufnahmeart.20.23257

**Comment by simoneOnFhir** [comment]
Umbenennen in "Abrechnungsart"
