### ISSUE TITLE
Bei BSNR und IK-Nummer und Standortnummer sollte „use“ auf „official“ festgesetzt sein.

### ISSUE THREAD

**Issue by simoneOnFhir** [hl7germany/basisprofil-de-r4#26]
Organisation.identifier

Bei BSNR und IK-Nummer und Standortnummer sollte „use“ auf
„official“ festgesetzt sein.

Eingereicht durch: Jörg Caumanns

**Comment by simoneOnFhir** [comment]
#29 beachten bei Modellierung der BSNR!

**Comment by alexzautke** [comment]
Bereits umgesetzt für IKNR und BSNR.
