### ISSUE TITLE
Abbildung von Diagnosetypen

### ISSUE THREAD

**Issue by alexzautke** [hl7germany/basisprofil-de-r4#261]
Kommentar eingereicht durch: Udo Siefker, Bettina Lieske, SAP SE
Kategorie: Vorschlag
Bezug im Dokument: Diagnosetypen
https://ig.fhir.de/basisprofile-de/stable/Ressourcen-Condition-TypenundRangfolgen.html

Existierende Formulierung: "Es wird nur auf das internationale CodeSystem verwiesen."
Änderungsvorschlag: "Ein weiteres Codesystem mit den für DE relevanten Werten einführen:
Krankenhaushauptdiagnose
Fachabteilungshauptdiagnose
DRG-Hauptdiagnose
DRG-Nebendiagnose
etc."
Kommentar / Begründung: "Dieses könnte dann sowohl für den Diagnose-Knoten im Encounter als auch für den (noch nicht existierenden) im Account verwendet werden."

**Comment by simoneOnFhir** [comment]
Die Dokumentation wurde angepasst, und ausdrücklich darauf verwiesen, dass an dieser Stelle nur Klinische Aspekte berücksichtigt werden. Die Abbildung der Abrechnungsrelevanten Diagnosetypen erfolgt auf der Ebene des Accounts.
