### ISSUE TITLE
Abbildung Hauptdiagnose

### ISSUE THREAD

**Issue by alexzautke** [hl7germany/basisprofil-de-r4#262]
Kommentar eingereicht durch: Udo Siefker, Bettina Lieske, SAP SE
Kategorie: Ablehnende Kritik
Bezug im Dokument: Beispiel: Hauptdiagnose
https://ig.fhir.de/basisprofile-de/stable/Ressourcen-DiagnosenCondition.html#Ressourcen-Condition-TypenundRangfolgen

Existierende Formulierung: "Beispiel: Hauptdiagnose"
Änderungsvorschlag: "Ein spezifisches Beispiel nehmen, dass dann mit dem unter #6 vorgeschlagenen CodeSystem modelliert werden kann."
Kommentar / Begründung: "Eine Hauptdiagnose ist unspezifisch, es sollte zwischen Krankenhaus- und Fachabteilungshauptdiagnose unterschieden werden. Diese müssen auf unterschiedlichen Ressource-Typen dokumentiert werden:
Fachabteilungshauptdiagnose auf Encounter
Krankenhaushauptdiagnose auf Account."

**Comment by simoneOnFhir** [comment]
Folgende Ergänzung zu dem Kapitel im IG hinzugefügt:
  Es ist zu beachten, dass hier nur klinische Aspekte abgebildet werden, also "Hauptdiagnose" im Sinne von "Fokus der 
  Behandlung". 
  Die Qualifizierung von Diagnosen im Kontext der Abrechnung wird derzeit noch nicht berücksichtigt und muss ggf. über 
  den Account dargestellt werden.
