### ISSUE TITLE
Verwendung des Begriffs Falls im Kontext der Aufnahme- oder Entlass-Diagnose

### ISSUE THREAD

**Issue by alexzautke** [hl7germany/basisprofil-de-r4#263]
Kommentar eingereicht durch: Udo Siefker, Bettina Lieske, SAP SE
Kategorie: Vorschlag
Bezug im Dokument: Diagnosetypen
https://ig.fhir.de/basisprofile-de/stable/Ressourcen-DiagnosenCondition.html#Ressourcen-Condition-TypenundRangfolgen

Existierende Formulierung: "Grundsätzlich gilt zu beachten, dass Attribute wie "Aufnahme- oder Entlass-Diagnose", sowie Rangfolgen von Diagnosen stets im Kontext eines Behandlungsfalles zu sehen sind. Sie werden daher als Eigenschaft des Encounters modelliert."
Änderungsvorschlag: "In dieser Formulierung nicht von Behandlungsfall sprechen"
Kommentar / Begründung: "Achtung: Fall = Account, Kontakt = Encounter, wie im IG bereits an anderer Stelle korrekt beschrieben: https://ig.fhir.de/basisprofile-de/stable/Ressourcen-AmbulanterstationrerFallKontaktEncounter.html"

**Comment by simoneOnFhir** [comment]
Die Formulierung wurde geändert auf:
"Grundsätzlich gilt zu beachten, dass Attribute wie "Aufnahme- oder Entlass-Diagnose", stets im Kontext eines stationären Aufenthaltes zu sehen sind."
