### ISSUE TITLE
Verwendung Encounter.diagnosis.rank

### ISSUE THREAD

**Issue by alexzautke** [hl7germany/basisprofil-de-r4#264]
Kommentar eingereicht durch: Udo Siefker, Bettina Lieske, SAP SE
Kategorie: Rückfrage
Bezug im Dokument: Diagnosetypen
https://ig.fhir.de/basisprofile-de/stable/Ressourcen-DiagnosenCondition.html#Ressourcen-Condition-TypenundRangfolgen

Kommentar / Begründung: "Was ist der DE-spezifische Anwendungsfall für diagnosis.rank im Encounter? In den uns bekannten Fällen ist eine Rangfolge auf Fallebene (Account) nötig. 
Zum Beispiel bei der Übergabe an den DRG-Grouper-"

**Comment by simoneOnFhir** [comment]
Der Verweis auf die Rangfolge wurde aus der Beschreibung und den Beispielen entfernt.
