### ISSUE TITLE
Differenzierung Selbstzahler Coverage-CodeSystem

### ISSUE THREAD

**Issue by alexzautke** [hl7germany/basisprofil-de-r4#270]
Kommentar eingereicht durch: Udo Siefker, Bettina Lieske, SAP SE
Kategorie: Vorschlag
Bezug im Dokument: Versicherungs-Informationen (Coverage)
in https://ig.fhir.de/basisprofile-de/stable/Coverage-CodeSystem.html 

Existierende Formulierung: "
Code	Display
GKV	gesetzliche Krankenversicherung
PKV	private Krankenversicherung
BG	Berufsgenossenschaft
SEL	Selbstzahler
SOZ	Sozialamt
GPV	gesetzliche Pflegeversicherung
PPV	private Pflegeversicherung
BEI	Beihilfe"
Änderungsvorschlag: Weitere Differenzierung des Selbstzahlers
Kommentar / Begründung: Es gibt diverse Fälle, in denen nicht der Patient als Selbstzahler, sondern andere Personen oder Organisationen als Rechnungsempfänger fungierten. Hier ein paar Beispiele:
- Organtransplantation: Dort ist dann der aus Sicht des Organspenders der Organempfänger (als Selbstzahler) der Rechnungsempfänger und wurde entsprechend als VV im Fall des Organspenders hinterlegt.
- Konsile für externe Krankenhäuser (z.B. Einstellungstests mit anonymer Rechnung an eine zentrale Hochschulstelle).
- Ausländische Patienten
Zusätzlich gibt es noch andere Kostenträger wie Bundeswehr, Polizei, Postbeamte / Postangestellte, … die alle ihre eigenen Regeln haben. 
Diese sind zwar alle „Selbstzahler“, aber sollten nicht zusammengefasst werden, um nachfolgende Prozesse steuern zu können.

**Comment by simoneOnFhir** [comment]
Hier muss Untersucht werden, in wie fern Abrechnungsregeln (die auch über Account.type getriggert werden könnten) von der eigentlichen Coverage (welche Leistungen sind abgedeckt) abgegrenzt werden. Die Coverage dient in erster Linie der Steuerung klinischer Workflows und der Prüfung, welche Leistungen ggf. vorab genehmingungspflichtig sind oder einer Kostenübernahmevereinbarung mit dem Patienten bedürfen. In wie fern die verschiedenen Selbstzahlerverhätnisse in dieser Hinsicht verschieden sind bedarf weiterer Prüfung. Wir nehmen das in die Liste der künftigen Weiterentwicklungen auf und warten auf Feedback und Erfahrungen aus der Umsetzung der IsiK-Spezifikation.

**Comment by alexzautke** [comment]
Duplikat. Siehe #254
