### ISSUE TITLE
Rückfrage Datentyp EBM-Leistung

### ISSUE THREAD

**Issue by alexzautke** [hl7germany/basisprofil-de-r4#271]
Kommentar eingereicht durch: Udo Siefker, Bettina Lieske, SAP SE
Kategorie: Rückfrage
Bezug im Dokument: ChargeItem
https://ig.fhir.de/basisprofile-de/stable/Ressourcen-AbrechnungsdatenLeistungsziffernChargeItem.html

Existierende Formulierung: "im DE-Profil für eine EBM-Leistung ist das element.definitionCanonical vom Typ canonical, während es im internationalen Profile vom Typ canonical(ChargeItemDefinition) ist. "
Änderungsvorschlag: "Sollte dies nicht derselbe Typ wie im internat. Profil sein und dann, im Falle der EBM-Leistung auch auf eine Leistung aus dem EBM-Katalog verweisen?"

**Comment by alexzautke** [comment]
Der Unterschied besteht allein im Rendering der Ressource. Der Snapshot ist korrekt. Support-Ticket an Firely für einen Feature-Request wird gestellt: Das Redering von canonical(TargetProfile) sollte gleich sein zu Reference(TargetProfile)

**Comment by simoneOnFhir** [comment]
Submitted as https://firely.atlassian.net/servicedesk/customer/portal/1/SD-894

**Comment by alexzautke** [comment]
Fixed in latest Simplifier release
