### ISSUE TITLE
Irreführende Verwendung von MUST und optional

### ISSUE THREAD

**Issue by tliebscher** [hl7germany/basisprofil-de-r4#32]
Wieso wird MUST verwendet, wenn es in der ursprünglichen VSDM Spezifikation um OPTIONAL ging?

https://simplifier.net/BasisprofilDE/patient-de-vsdm-0.2/~details
...
Patient Ressource im Kontext des deutschen VSDM (Versichertenstammdatenmanagement, "eGK-Datensatz"). Elemente, die als "must-support" gekennzeichnet sind, repräsentieren die **optionalen** Informationen aus der der VSDM-Spezifikation.

**Comment by lhitc** [comment]
Dürfte mit #84 geklärt sein (kein must-support in den Basisprofilen).
Vor Schließen des Issues sollte dies aber für ein mögliches, sehr spezifisches, VSDM-Profil noch einmal diskutiert werden.

**Comment by alexzautke** [comment]
https://chat.fhir.org/#narrow/stream/224725-german.2Fcommitters

**Comment by alexzautke** [comment]
Beschluss TC FHIR 18.09.2020: VSDM Patient wird nicht nach R4 portiert. Relevante Organisationen und Projekte geben schon verbindliche Profile vor. Es werden weiterhin nur die notwendigen Datentyp-Profile publiziert in den Basisprofilen.
