### ISSUE TITLE
Abbildung Behinderungsgrad in FHIR

### ISSUE THREAD

**Issue by simoneOnFhir** [hl7germany/basisprofil-de-r4#335]
Observation.code = SNOMED-Code 116149007 (Disability percentage (finding))
(Es erfolgt dazu noch Abstimmung mit TC Terminologien)
Observation.valueQuantity = 10-100 {percent}
Invariante, die prüft, dass nur Zehnerschritte zwischen 10 und 100 möglich sind
Observation.component.code enthält Binding auf die Deutschen Merkzeichen
Observation.component.valueBoolean (fixed=true) 0..1
ZUSÄTZLICH wird eine Empfehlung formuliert, wie die Merkzeichen auf https://www.hl7.org/fhir/v3/PersonDisabilityType/cs.html gemappt werden können (unsinnige Flags wie “Rundfunk/Fernsehen”, “1. Klasse” etc fallen ggf. raus) und in der Extension disability http://hl7.org/fhir/extension-patient-disability.html zu den Patientenstammdaten hinzugefügt werden können.

Siehe Protokoll TC-FHIR-Meeting vom 22.07.2021:
https://docs.google.com/document/d/10Lpoier8jektLdqVf7FQ_a8zTeDtwaa43Xa-KK0MFqY/edit#heading=h.1g1qhjy4azg6

**Comment by alexzautke** [comment]
Dokumentation im IG ist noch offen

**Comment by alexzautke** [comment]
IG Seite hinzugefügt
