### ISSUE TITLE
http://fhir.de/StructureDefinition/observation-de-vitalsign-blutdruck Components 0..1

### ISSUE THREAD

**Issue by mmreith** [hl7germany/basisprofil-de-r4#341]
Bei der damaligen Besprechung mit Medizinern (Alex war auch dabei) wurde angemerkt, dass in Notfallsituationen auch nicht alle components (systolisch & diastolisch) verfügbar sein können, daher bitte 1..1 -> 0..1

**Comment by alexzautke** [comment]
Dies wurde in der Entwicklung der Profile verworfen, da die internationalen Profile hier verpflichtende .component-Elemente haben. Eine Abweichung wäre hier hinderlich. Aktuell findet sich hier eine Diskussion statt, gerne den Use Case dort nochmal anbringen: https://chat.fhir.org/#narrow/stream/179166-implementers/topic/Vital.20Signs.20Profile.20-.20clarity.20on.20applicability

**Comment by alexzautke** [comment]
Zudem ist im internationalen Profil nur der Code der Komponente verpflichtend, jedoch nicht die valueQuantity Angabe der Systole oder Diastole. Mein Vorschlag wäre daher Observation.component.dataAbsentReason explizit (nicht als Extension!) anzugeben.

**Comment by mmreith** [comment]
stimmt...übersehen
