### ISSUE TITLE
Link falsch 

### ISSUE THREAD

**Issue by simoneOnFhir** [hl7germany/basisprofil-de-r4#361]
"Die canonical URLs dienen zwar nur der eindeutigen (Re-)Identifikation einer Ressource über Systemgrenzen hinweg, unabhängig von deren physikalischer Adresse, durch einen Redirect von http://fhir.de auf http://simplifier.org sind jedoch die technischen Voraussetzungen gegeben, um alle in diesem Leitfaden definierten URLs bei der Eingabe in einen Browser direkt zu der Spezifikation dieser Resource auf Simplifier aufzulösen."
...muss Simplifier.NET heißen!

**Comment by alexzautke** [comment]
Done
