### ISSUE TITLE
IKNR-Profil sollte einen Type vorgeben

### ISSUE THREAD

**Issue by lhitc** [hl7germany/basisprofil-de-r4#40]
Der Type für IKNR sollte festgelegt sein, auch wenn type nicht 1..1 vorgeschrieben ist.

**Comment by simoneOnFhir** [comment]
PRN | Provider number ?
http://hl7.org/fhir/valueset-identifier-type.html

**Comment by alexzautke** [comment]
"XX" Organization identifier muss verpflichtend angegeben werden
