### ISSUE TITLE
Vitalparameter: Einheitliche Bindings + Pattern für valueQuantity

### ISSUE THREAD

**Issue by alexzautke** [hl7germany/basisprofil-de-r4#400]
Motion: 
1. Binding auf valueQuantity.code wird auf valueQuantity Ebene hochgezogen (ersetzt kompatibel das Binding aus dem Vitalparameter-Basisprofil)
2. Patterns auf valueQuantity.code werden ebenfalls auf valueQuantity-Ebene hochgezogen.

**Notes:**
1..1 Constraint auf unit ist nicht nachvollziehbar wird jedoch aus Kompatibilitätsgründen zu den int. Profilen beibehalten.
Vote: 6-0-0

**Comment by alexzautke** [comment]
@ylboerner Bitte noch Aufwand dokumentieren

**Comment by ylboerner** [comment]
Aufwand: 0.5 Stunden
