### ISSUE TITLE
MHD Profilierung für ePA

### ISSUE THREAD

**Issue by jmehlbrech** [hl7germany/basisprofil-de-r4#41]
Hallo,

es wäre denke ich hilfreich - auch im Sinne einer besseren Standardisierung - wenn die ePA-Specs der Gematik in eine MHD-Profilierung einfließen könnten - insbesondere die ValueSets/Codesysteme und die uuids. Der Bedarf dürfte allgemein entstehen, da ePA auf dem deutschen Gesundheitsmarkt einen Standard setzen wird - und der Dokumentenaustausch das in der Konsequenz berücksichtigen muss.

Grüße,
Jörg Mehlbrech

**Comment by simoneOnFhir** [comment]
Siehe auch https://chat.fhir.org/#narrow/stream/179183-german-(d-a-ch)/topic/XDS.20Metadaten.20in.20FHIR
und Issue #105

**Comment by alexzautke** [comment]
Siehe https://hl7germany.atlassian.net/browse/HFB-31
