### ISSUE TITLE
Falsche Benennung des Identifier Profils IdentifierIknr auf der IG Seite

### ISSUE THREAD

**Issue by abiernat-cerner** [hl7germany/basisprofil-de-r4#419]
Auf der Seite https://ig.fhir.de/basisprofile-de/stable/InstitutionskennzeichenIKNR.html wird das Profil mit  **Name: IdentifierPkv**  statt **Name: IdentifierIknr** benannt.

**Comment by alexzautke** [comment]
Vielen Dank für den Hinweis. Der Name wurde korrigiert.
