### ISSUE TITLE
Condition falsche Bindings

### ISSUE THREAD

**Issue by mmreith** [hl7germany/basisprofil-de-r4#42]
Im Profil http://fhir.de/StructureDefinition/condition-de-icd10

Bodysite binding an ein Codesystem http://fhir.de/CodeSystem/kbv/s_icd_seitenlokalisation (required)

Falsche Bezeichnung https://fhir.kbv.de/ValueSet/KBV_VS_SFHIR_ICD_SEITENLOKALISATION

**Comment by lhitc** [comment]
Die Übernahme der von der KBV vergebenen Namen für KBV-Terminologie-Ressourcen steht noch aus.

**Comment by patrick-werner** [comment]
fixed through #45
