### ISSUE TITLE
Hinweis auf die Lizenzbedinungen von FHIR in FAQ mit aufnehmen

### ISSUE THREAD

**Issue by alexzautke** [hl7germany/basisprofil-de-r4#423]
Die Frage ob FHIR lizensiert werden muss und/oder die Flamme als Logo verwendet werden kann, sollte in die FAQ mit aufgenommen werden. Hinweis auf https://www.hl7.org/fhir/license.html einfügen.

**Comment by ylboerner** [comment]
Hinzugefügt: https://simplifier.net/guide/basisprofil-de-r4/Anwendungshinweise-FAQ?version=current
