### ISSUE TITLE
Falsches Binding und Codesystem in Extension Diagnosesicherheit

### ISSUE THREAD

**Issue by mmreith** [hl7germany/basisprofil-de-r4#43]
Im Profil https://simplifier.net/Basisprofil-DE-R4/ICD10GMDiagnosesicherheit

Ist noch nicht das neue Valueset und Codesystem verwendet worden.
https://fhir.kbv.de/CodeSystem/KBV_CS_SFHIR_ICD_DIAGNOSESICHERHEIT | https://fhir.kbv.de/ValueSet/KBV_VS_SFHIR_ICD_DIAGNOSESICHERHEIT

**Comment by lhitc** [comment]
Die Übernahme der von der KBV vergebenen Namen für KBV-Terminologie-Ressourcen steht noch aus.

**Comment by patrick-werner** [comment]
fixed through #45
