### ISSUE TITLE
DiagnoseTyp: Umbenennung Behandlungsdiagnose -> Behandlungsrelevante Diagnose, Anpassung Display Value für refferal-diagnosis

### ISSUE THREAD

**Issue by alexzautke** [hl7germany/basisprofil-de-r4#432]
Schreiben der DKG:

im Folgenden erhalten Sie wie besprochen unsere Rückmeldung / Anforderungen zu den Diagnosetypen und Befundtypen.

In der aktuellen Version des Krankenhausentlassbriefs sind über das Informationsmodell die folgenden Arten von Diagnosen vorgesehen, für die geeignete ISiK-Encounter-Diagnosetypen zu wählen bzw. zu definieren wären.

Aktuell sind im Informationsmodell keine Codes festgelegt. Die Einteilung ergibt aus den jeweiligen Blöcken im ART-DECOR / Informationsmodell des Krankenhausentlassbriefs, in denen Diagnosen vorgesehen sind:

  1.  Einweisungsdiagnosen (i.A. aus der Krankenhauseinweisung / Muster 2)

  1.  Aufnahmediagnosen (vom Krankenhaus im Rahmen der Aufnahme festgelegt)

  1.  Diagnosen, die für die Behandlung während des stationären Aufenthalts relevant waren. Im Krankenhausentlassbrief treten diese im Element „Diagnosen“ auf und sind mit einem Ranking verbunden („wichtigste zuerst“), das bei der Anzeige berücksichtigt werden soll (Operationalisierungshinweis im MIO) - für die anderen Arten von Diagnosen ist kein Ranking vorgesehen. Könnte evtl. über „Behandlungsdiagnose“ bzw. „Entlassungsdiagnose“ codiert werden, bitte beachten Sie aber unsere Anmerkung zum Begriff „Behandlungsdiagnose“

  1.  Anamnestische Diagnosen (z.B. Im Gespräch erhoben oder aus dem NFD übernommen). Dieser Typ müsste ergänzt werden. Behandlungsrelevante Diagnosen werden unter 3. aufgeführt, auch wenn sie im Rahmen der Anamnese erhoben wurden.

Hinsichtlich der im ISiK-Encounter vorgesehenen Diagnosetypen haben wir die folgenden Anmerkungen:

   *   DiagnoseTyp:

        *   Behandlungsdiagnose: Dies ist ein quartalsbezogener Abrechnungsbegriff aus dem niedergelassenen Bereich https://www.kbv.de/media/sp/Ambulante_Kodierunterstuetzung.pdf sowie für ambulante Fälle gemäß der Vereinbarung nach § 301 Abs. 3 SGB V https://gkv-datenaustausch.de/leistungserbringer/krankenhaeuser/krankenhaeuser.jsp Insofern ist die Bezeichnung für den stationären Krankenhausentlassbrief nicht geeignet, da wir uns dort im stationären Bereich bewegen und keine Abrechnungsinformationen abbilden. Ggf. könnte man eine entsprechende Erläuterung in ISiK-Encounter ergänzen oder die Übersetzung „Behandlungsrelevante Diagnose“ wählen.

        *   Überweisungsdiagnose: ist nur im niedergelassenen / ambulanten Bereich relevant. Die Bezeichnung ist für den stationären Krankenhausentlassbrief nicht geeignet. Die Überweisung sollte von der Einweisung unterschieden werden.

   *   DiagnoseSubTyp:

        *   Abteilungshauptdiagnose: Der Entlassbrief bezieht sich auf den gesamten Aufenthalt. Insofern sollte eine Diagnose im Krankenhausentlassbrief nicht als Abteilungshauptdiagnose gekennzeichnet werden können.

        *   Operationsdiagnose: Im Informationsmodell des Krankenhausentlassbrief nicht als Sonderkennzeichnung vorgesehen (wird über die behandlungsrelevanten Diagnosen sowie die Angaben zur durchgeführten Prozedur abgebildet).

        *   Bei Infektionsschutzdiagnose ist nicht ganz klar, was gemeint ist. Im Krankenhausentlassbrief müssen Infektionen und Besiedelungen durch multiresistente Erreger erfasst werden (ggf. auch als ICD-Codes). Daneben werden auch z.B. Corona-Infektionen erfasst (meldepflichtige Krankheiten und Erregernachweise nach IfSG). Entsprechende Sonderkennzeichnungen sind im Modell des Krankenhausentlassbrief nicht explizit vorgesehen, aber ggf. über Hinweistexte abbildbar. Für Infektionen und Besiedelungen durch multiresistente Erreger existieren zudem weitere Datenfelder.

   *   Eine Notwendigkeit der Unterteilung in Typ und SubTyp ist für den Krankenhausentlassbrief aus unserer Sicht nicht zwingend erforderlich.

   *   Im Hinblick auf die abrechnungsbezogenen Diagnosetypen in ISiK Account, die für den Krankenhausentlassbrief dem Wesen nach nicht geeignet sind, verweisen wird insbesondere auf die Vereinbarung nach § 301 Abs. 3 SGB V für die stationäre und ambulante Versorgung im Krankenhaus.

**Comment by simoneOnFhir** [comment]
Vorschlag für eine Motion zur Anpassung der Basisprofile an die Anforderungen der DKG:

**1. Einweisungsdiagnosen (i.A. aus der Krankenhauseinweisung / Muster 2)** 
Abbildbar mit  DiagnoseTyp = referral-diagnosis
Change: Anpassung des Displaywertes auf"Einweisungs-/Überweisungsdiagnose"
Anmerkung: Die Differenzierung zwischen Ein- und Überweisung ist vornehmlich duch die unterschiedliche Abrechnung begründet und hat keine Auswirkung auf die medizinische Bewertung der Diagnose.

**2. Aufnahmediagnosen (vom Krankenhaus im Rahmen der Aufnahme festgelegt)**
Abbildbar mit DiagnoseTyp = treatment-diagnosis & DiagnoseSubtyp = AD
Change: -/-

**3. Diagnosen, die für die Behandlung während des stationären Aufenthalts relevant waren.** 
Abbildbar mit DiagnoseTyp = treatment-diagnosis
Change: Anpassung des Displaywertes auf "Behandlungsrelevante Diagnosen"

**4. Anamnestische Diagnosen**
Abbildbar mit Condition.encounter
Change: -/-
Anmerkung: Anamnestische Diagnosen, die keine behandlungsrelevanz im Kontext eines Encounters haben (sonst wären es behandlungsrelevante diagnosen) werden nur über Condition.encounter in einen Fallkontext gestellt. Sofern sie keine besondere Bedeutung im Kontext des Encounters haben, muss auch keine Rückverlinkung und Typisierung erfolgen.
Mittels Condition.clinicalStatus kann zwischen abgeheilten und Dauerdiagnosen in der Anamnese unterschieden werden.
Ob es sich um eine Eigen- oder Fremdanamnese handelt, kann über Condition.asserter abgebildet werden.

**Infektionsschutzdiagnose:**
Hier sollte die Beschreibung in den Basisprofilen (einschl. Use Case) verbessert werden.
Wie ist der Zusammenhang mit dem Kennzeichen "Infectious" im ICD-10 ClamL? 
Was geschieht mit nicht meldepflichtigen (?) Infektionen wie MRSA?

**Diagnosetypen im Account:**
Abgleich mit §301-Datensatz sollte durchgeführt werden.

**Comment by alexzautke** [comment]
Hinweis hinzugefügt: https://simplifier.net/guide/basisprofil-de-r4/Encounter-ValueSets?version=current
