### ISSUE TITLE
BSNR Identifier sollte auch als Identifier für Location geführt werden

### ISSUE THREAD

**Issue by simoneOnFhir** [hl7germany/basisprofil-de-r4#433]
Unterschiedliche Standorte haben versch. BSNRs, daher ist der Identifier auch für die Identifikation von Locations relevant.

**Comment by simoneOnFhir** [comment]
Im IG fehlt auch unter dem Kapitel "Identifier für Location" noch die Refernz auf die Standortnummer:
https://simplifier.net/Basisprofil-DE-R4/Standortnummer--DKG

**Comment by alexzautke** [comment]
Fixed. Zeitaufwand: 15min.
