### ISSUE TITLE
ValueSet MehrfachkodierungsKennzeichen Status: Draft, Experimental: True

### ISSUE THREAD

**Issue by hhund** [hl7germany/basisprofil-de-r4#434]
Das ValueSet `http://fhir.de/ValueSet/icd-10-gm-mehrfachcodierungs-kennzeichen` Version 1.3.2 ist mit `status: draft` und `experimental: true` definiert.

https://github.com/hl7germany/basisprofil-de-r4/blob/d07532d55fb0e22cac7049675d76adafc32d1eb1/terminologie/valuesets/ValueSet-icd-mehrfachkodierungs-kennzeichen.xml#L9-L10

Bug or feature?

**Comment by alexzautke** [comment]
Ich denke es ist ein Feature 😅 Wir wollten erstmal Feedback hierzu einholen. Bisher ist dies aber noch ausgeblieben.

**Comment by hhund** [comment]
Da das ValueSet inzwischen in diversen Profilen, direkt oder indirekt Verwendung findet, die entweder mit `status = active` gekennzeichnet sind oder bei denen das `experimental = true` Kennzeichen fehlt, könnte man argumentieren, dass sich das mit dem Feedback erledigt hat.

Insgesamt sollte man bei Releases vermutlich darauf achten, dass Ressourcen, die mit `status = active` oder ohne `experimental = true` gekennzeichnet sind, nicht von anderen Ressourcen abhängen, die diesen Zustand noch nicht erreicht haben.

Ich würde daher argumentieren, dass das ValueSet `http://fhir.de/ValueSet/icd-10-gm-mehrfachcodierungs-kennzeichen` und die Coding-Extension `http://fhir.de/StructureDefinition/icd-10-gm-mehrfachcodierungs-kennzeichen` einen Bug haben.

**Comment by alexzautke** [comment]
Mir wäre kein Projekt bekannt, dass das ValueSet oder die Extension bereits produktiv nutz. Das MII Profil Version 2.0 wurde noch nicht offiziell freigegeben. ISiK 2.0 ebenfalls.

**Comment by hhund** [comment]
Für mein Argument ist es egal, ob das ValueSet produktiv eingesetzt wird oder nicht. Meiner Meinung nach, können Ressourcen grundsätzlich nicht `active` sein, wenn sie von Ressourcen abhängen, die selber nicht `active` sind. Gleiches gilt entsprechend auch für den `experimental` Zustand. Ich würde daher dafür plädieren wollen, dass innerhalb eines Implementation Guide Release von einander abhängige Ressourcen auch zu einander kompatible Zustände von `status` und `experimental` haben sollten.

Um aber noch ein Beispiel für ein Projekt zu nennen, in dem indirekt das `MehrfachkodierungsKennzeichen` ValueSet produktiv verwendet wird: **NUM-CODEX** (de.gecco).

Abhängigkeit beispielsweise via:
* http://fhir.de/StructureDefinition/icd-10-gm-mehrfachcodierungs-kennzeichen
    IG: de.basisprofil.r4 | 1.0.0
    * http://fhir.de/StructureDefinition/CodingICD10GM
        IG: de.basisprofil.r4 | 1.0.0
        * https://www.medizininformatik-initiative.de/fhir/core/modul-diagnose/StructureDefinition/Diagnose
            IG: de.medizininformatikinitiative.kerndatensatz.diagnose | 2.0.0-alpha3
            * https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/gecco-base-condition
                IG: de.gecco | 1.0.5
                * https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/chronic-lung-diseases
                    IG: de.gecco | 1.0.5

Prinzipiell könnte man das hier natürlich ignorieren, da NUM-CODEX ein Alpha Release der MII verwendet, aber für mein Argument ist das ja, wie gesagt, auch irrelevant.

**Comment by alexzautke** [comment]
Wir werden dazu übergehen auf eine Art Maturity Level umzusteigen. Jedes Profil sollte z.B. eine Angabe enthalten, ob es in anderen nationalen Projekten bereits produktiv verwendet wird. Die Änderung wird wie vorgeschlagen umgesetzt.
