### ISSUE TITLE
Test des pre-release packages mit hapi

### ISSUE THREAD

**Issue by patrick-werner** [hl7germany/basisprofil-de-r4#437]
- [ ] in latest jpa starter hapi  per config pre-release package laden
- [ ] test mit latest fhir.core dependency (um Bug in veraltetem Java Validator auszuschließen)

Während des DevDays Connectathons gab es Fehler beim Laden des Vitalparameter Moduls (während Snapshotgeneration: "named slice in wrong order") welche mutmaßlich durch das Basisprofil

**Comment by alexzautke** [comment]
Java validator in der Version 5.6.39 ist happy mit den Profilen

**Comment by alexzautke** [comment]
Siehe https://hl7germany.atlassian.net/browse/HFB-35
