### ISSUE TITLE
Version der DEUEV CS

### ISSUE THREAD

**Issue by mmreith** [hl7germany/basisprofil-de-r4#439]
Hallo @patrick-werner @alexzautke 

seit der Version 1.2.0 der hl7-Basis werden die DEUEV*-CS mit der Version der Basis (z.b. 1.2.0) geführt ,statt wie früher 

DeuevAnlage6Vorsatzworte | http://fhir.de/CodeSystem/deuev/anlage-6-vorsatzworte | **2.30** | CodeSystem
DeuevAnlage7Namenszusaetze | http://fhir.de/CodeSystem/deuev/anlage-7-namenszusaetze | **2.25** | CodeSystem
DeuevAnlage8Laenderkennzeichen | http://fhir.de/CodeSystem/deuev/anlage-8-laenderkennzeichen | **2.56**

Fehler oder?

**Comment by alexzautke** [comment]
Siehe https://hl7germany.atlassian.net/browse/HFB-28
