### ISSUE TITLE
Fehlerhafter RegEx bei IK Profil

### ISSUE THREAD

**Issue by dhufnagel** [hl7germany/basisprofil-de-r4#455]
Bei dem Constraint ik-1 fehlt beim Regex der Start- und Endmarker. Somit wird eine Nummernfolge kleiner 8 Stellen als falsch erkannt, eine Nummernfolge größer 8 Stellen aber immer als korrekt erkannt, da eine diese immer auch eine 8-stellige Nummernfolge beinhaltet. Es wird sogar eine Ziffernfolge mit beinhalteter Nummernfolge als korrekt validiert (JKA987654321-.,).

**Comment by patrick-werner** [comment]
Vielen Dank für ihren Kommentar & PR.
Die Anmerkung ist korrekt, die fehlenden Marker sind im FHIR Java Validator bislang nicht aufgefallen, da die Java Implementierung regex per `matches()` nutzt(e).

**Comment by dhufnagel** [comment]
Der FHIR Validator erkennt genau die Folge "JKA987654321-.," als valide.

**Comment by dhufnagel** [comment]
Schön, dass man commits einfach nochmal neu selbst macht, um nicht die Contributor Liste mit externen zu "verunreinigen". Man hätte die weiteren Änderungen der fehlenden Star und endmarker auch auf dem PR commit aufbauen können.
So funktioniert Open source nicht uns man vergrault sich contributers, da ihre Arbeit nicht entsprechend honoriert wird. Ich jedenfalls habe keine Lust mehr Fehler für "euch" zu beheben 🤷

**Comment by alexzautke** [comment]
Hi @dhufnagel, es tut mir leid, dass ich nicht genauer Bescheid gegeben habe wieso der PR nicht gemerged wurde. Die Build Pipeline funktioniert im Projekt nicht sobald ein PR von einem Fork aus gestellt wird. Die hinterlegten GitHub Secrets werden nicht geteilt und der Build schlägt fehl. Es steht auf meiner ToDo List, ich wollte aber das Ticket nicht so stehen lassen.

**Comment by alexzautke** [comment]
Tut mir leid, auf die Idee mit dem Cherry Picken des Commits bin ich nicht gekommen. Ich werde darauf achten. Gelobe Besserung :)
