### ISSUE TITLE
category slice: * category[vs-cat] vs * category[VSCat]

### ISSUE THREAD

**Issue by patrick-werner** [hl7germany/basisprofil-de-r4#459]
Obs.category in den dt. Vitalsigns enthalten den sliceName: `vs-cat`, Vitalsigns international verwendet hier `VSCat`
Um hier unnötige Konfusion und eine einfache Implementierbarkeit zu vermeiden, bzw. ermöglichen sollte der SliceName auf den internationalen SliceName angepasst werden

**Comment by alexzautke** [comment]
Siehe https://hl7germany.atlassian.net/browse/HFB-12
