### ISSUE TITLE
Basisprofil Diagnose erzeugt Best Practice warning

### ISSUE THREAD

**Issue by patrick-werner** [hl7germany/basisprofil-de-r4#46]
Ursprung: https://chat.fhir.org/#narrow/stream/179183-german-(d-a-ch)/topic/Basisprofile.20Diagnose

Die Angabe der Äquivalente empfiehlt ein nicht befüllen von clinical status im Falle einer Ausschlussdiagnose. Dies führt leider zu einer best practice warning: con-3

Vorschlag Änderung zu:

"A" (ausgeschlossen) => clinicalStatus = active, verificationStatus="refuted"

**Comment by simoneOnFhir** [comment]
Diskussion hier (international):
https://chat.fhir.org/#narrow/stream/179166-implementers/topic/AllergyIntolerance.20-.20clinical.20status.20of.20refuted.20allergies

**Comment by simoneOnFhir** [comment]
Diskussion national: https://chat.fhir.org/#narrow/stream/179183-german-(d-a-ch)/topic/Basisprofile.20Diagnose
