### ISSUE TITLE
Constraint severity passend setzen

### ISSUE THREAD

**Issue by HendrikGematik** [hl7germany/basisprofil-de-r4#460]
Diverse "wichtige" Constraints haben eine Einstufung "Warning", obwohl bei Constraintverletzung von einem harten Fehler ausgegangen werden kann. Bsp.:
`<constraint><key value="kvid-1"/><severity value="warning"/>`

Ist eine KVNR falsch formatiert, ist es keine KVNR, das Individuum mithin nicht identifizierbar. Hier kann von einem Fehler ausgegangen werden, sodass ein Validator besser einen Error meldet.

Betrifft weitere Identifier-Constraints für IK, LANR, ZANR.

**Comment by alexzautke** [comment]
Konsens im TC: Basisprofile sollen diese Entscheidung nicht allen abgeleiteten UseCases aufzwingen, die Verschärfung der Constraints ist – bei Bedarf – die Aufgabe von abgeleiteten Profilen. 
Motion: Simone Heckmann/Max Reith 
Vote: 8-0-0

**Comment by alexzautke** [comment]
Siehe TC Protokoll vom 25.08.2022

**Comment by alexzautke** [comment]
Ich verstehe das Problem, dass der Text hier zunächst erstmal falsch erscheint. Die Severity kann ich in einem abgeleiteten Profil ändern, den Text nicht mehr. Dann wäre es verwirrend, wenn im Text "SOLLTE" steht aber es als Error interpretiert wird.
