### ISSUE TITLE
Falsche Bezeichnung Extension Geschlecht

### ISSUE THREAD

**Issue by abiernat-cerner** [hl7germany/basisprofil-de-r4#462]
Im aktuellen IG ist auf der Seite https://simplifier.net/guide/basisprofil-de-r4/ExtensionsfrPatient?version=current Abschnitt Geschlecht ein falscher Bezeichner:

Name: **Extension-address-ags** ([Simplifier Projekt Link](https://simplifier.net/resolve?canonical=http://fhir.de/StructureDefinition/gender-amtlich-de&scope=de.basisprofil.r4@1.4.0))

**Comment by alexzautke** [comment]
Fehler wurde behoben. Danke!
