### ISSUE TITLE
Im IG sollte bei der Beschreibung der Fallarten auch auf das VS Kontaktart verlinkt werden.

### ISSUE THREAD

**Issue by simoneOnFhir** [hl7germany/basisprofil-de-r4#468]
...ist sonst schwer zu finden....

Hier: https://simplifier.net/guide/basisprofil-de-r4/Ressourcen-AmbulanterStationaererFall?version=current
sollte ein link zu finden sein auf 
hier: http://fhir.de/ValueSet/kontaktart-de bzw. https://simplifier.net/basisprofil-de-r4/kontaktartde

**Comment by alexzautke** [comment]
Siehe https://hl7germany.atlassian.net/browse/HFB-24
