### ISSUE TITLE
Definition "Basis-Profile" schärfen

### ISSUE THREAD

**Issue by simoneOnFhir** [hl7germany/basisprofil-de-r4#475]
https://simplifier.net/guide/leitfaden-de-basis-r4/ig-markdown-Anwendungshinweise-AbleitungEigenerProfileBasisprofilen?version=current

Hier muss spezifischer klar gemacht werden, dass die Basisprofile UseCase-unabhängig und -übergreifend sind und nicht unmittelbar implementierbar sind.

Außerdem: Dead Link am Ende der Seite!

**Comment by alexzautke** [comment]
Siehe https://hl7germany.atlassian.net/browse/HFB-23
