### ISSUE TITLE
URL in IG not rendered

### ISSUE THREAD

**Issue by f-peverali** [hl7germany/basisprofil-de-r4#476]
In der Current Version des Leitfadens/IG werden URLs nicht aufgelöst.

Siehe Message: "Command 'pagelink' could not render: Page not found. "

Z.B. an folgenden Stellen:
-https://simplifier.net/guide/leitfaden-de-basis-r4/ig-markdown-Datentypen-Coding?version=current#ig-markdown-Datentypen-Coding-Alpha-ID
-https://simplifier.net/guide/leitfaden-de-basis-r4/ig-markdown-UeberDiesenLeitfaden?version=current 
...
... es scheint der gesamte Leitfaden betroffen zu sein.

**Comment by alexzautke** [comment]
@ylboerner Magst du dir das anschauen? Wenn du zu viele ToDos auf deiner Liste hast, sag Bescheid.

**Comment by alexzautke** [comment]
Siehe https://hl7germany.atlassian.net/browse/HFB-11
