### ISSUE TITLE
ICD-O-3 System (Supplement)

### ISSUE THREAD

**Issue by patrick-werner** [hl7germany/basisprofil-de-r4#48]
Es gibt derzeit keine definierte URI für ICD-O-3 , Anfrage international hier: https://chat.fhir.org/#narrow/stream/179166-implementers/topic/ICD-O-3.20CodeSystem.20URI

Da ICD-O-3 "Dimdi Edition" bis auf die Displayvalues identisch mit der WHO Version ist könnten wir ein CodeSystem Supplement für die internationale Version erstellen.
Da die Lizenzierungsfrage aber international noch komplexer ist als in DE könnten wir auch vorerst ein deutsches ICD-O-3 CodeSystem, bzw. CodeSystem URI definieren.

**Comment by alexzautke** [comment]
Out of scope für die Basisprofile. Bitte neues Ticket für die Basisprofile Onkologie anlegen. Siehe https://github.com/hl7germany/basisprofil-onkologie-R4
