### ISSUE TITLE
Coverage: abrechnendeKrankenkasse als Extension statt Slice

### ISSUE THREAD

**Issue by simoneOnFhir** [hl7germany/basisprofil-de-r4#50]
aus Gespräch mit GKV:

Anstelle zweier Slices auf Payor für "Kostenträger" und "abrechnendes IK" besser eine optionale Extension für abrechnendes IK und Payor 1..1

	<payor>
		<extension url=".../abrechnendeIK">
			<identifier>
				<system value="http://fhir.de/NamingSystem/arge-ik/iknr" />
				<value value="756756325" />
			</identifier>
		</extension>
		<identifier>
			<system value="http://fhir.de/NamingSystem/arge-ik/iknr" />
			<value value="756756324" />
		</identifier>
		<display value="Krankenkasse A" />

	</payor>

**Comment by simoneOnFhir** [comment]
https://chat.fhir.org/#narrow/stream/179183-german-(d-a-ch)/topic/.5BBASIS.5D.20Issue.2350.3A.20Abrechnende.20KK

**Comment by simoneOnFhir** [comment]
Bei dieser Gelegenheit muss auch folgender Bug korrigiert werden: Die Kardinalität von Payor.identifier ist derzeit 0..* im Profil, darf aber gar nicht sein, weil Reference.identifier gem. Spezifikation 0..1 ist!!!!

**Comment by alexzautke** [comment]
Ist ein Bug in Simplifier, gefixt in einer der nächsten Releases. Wurde bereits in der .NET API behoben.
