### ISSUE TITLE
Im IG Verweis auf Einwilligungsmanagement aktualisieren

### ISSUE THREAD

**Issue by lhitc** [hl7germany/basisprofil-de-r4#501]
Auf https://ig.fhir.de/basisprofile-de/stable/Ressourcen-VerweiseaufExterneLeitfaeden.html wird derzeit noch auf das Simplifier-Projekt zum Einwilligungsmanagement verwiesen. Korrekt wäre inzwischen der Verweis auf den stabilen IG:
https://ig.fhir.de/einwilligungsmanagement/stable/Home.html

**Comment by alexzautke** [comment]
Siehe https://hl7germany.atlassian.net/browse/HFB-51
