### ISSUE TITLE
Informationen über Organization fehlen

### ISSUE THREAD

**Issue by lhitc** [hl7germany/basisprofil-de-r4#503]
Zur Organization existeren im IG bisher nur Hinweise unter den Datentypen bezüglich der Identifier.

Es sollte auch im Abschnitt "Ressourcen" einen Punkt zu Organization geben.
Hier sollte z.B. darauf eingegangen werden, wie verschiedene Organisationsarten unterschieden werden können.
Im entsprechenden KBV-Basisprofil ( https://simplifier.net/base1x0/kbv_pr_base_organization ) existieren bereits Slices für Organization.type mit verschiedenen Bindings. Diese fokussieren allerdings ausschließlich auf medizinische Einrichtungsarten bzw. Fachrichtungen.
Es sollte auch eine standardisierte Vorgabe existieren, weitere Organisationsarten abzubilden. Dies mindestens aus dem Gesundheitswesen (z.B. auch Kostenträger), evtl. unter Nutzung der IK-Klassifikation https://simplifier.net/basisprofil-de-r4/argeikklassifikationvs 

Dieses VS scheint übrigens im IG nicht benannt zu sein (lediglich das CS).

**Comment by alexzautke** [comment]
Siehe https://hl7germany.atlassian.net/browse/HFB-52
