### ISSUE TITLE
Kein Git Tag für Version 1.4.0

### ISSUE THREAD

**Issue by Boereck** [hl7germany/basisprofil-de-r4#506]
Hallo, das Paket für Version 1.4.0 ist bereits längst [veröffentlicht](https://simplifier.net/packages/de.basisprofil.r4/1.4.0), aber der entsprechende Tag, auf diesem GitHub Repository fehlt.

**Comment by alexzautke** [comment]
Danke für den Hinweis, der Tag findet sich nun hier: https://github.com/hl7germany/basisprofil-de-r4/releases/tag/v1.4.0
