### ISSUE TITLE
KVK Identifier Profil

### ISSUE THREAD

**Issue by mmreith** [hl7germany/basisprofil-de-r4#51]
Hallo,

ein KVK Identifierprofil wäre sehr gut, da es immer noch sehr viele Leute mit einer KVK gibt (Sonderkostenträger)

Diese könnte analog zu https://simplifier.net/basisprofil-de-r4/identifierpkv aufgebaut sein. 

also eine KVK Nummer die im Rahmen einer Organisation gültig ist...

Gruß Max

**Comment by simoneOnFhir** [comment]
https://chat.fhir.org/#narrow/stream/179183-german-(d-a-ch)/topic/.5BBASIS.5D.20Issue.2351.3A.20KVK-Identifier

**Comment by alexzautke** [comment]
Erstmal kein Bedarf mehr.
