### ISSUE TITLE
 basisprofil-de-r4/terminologie/namingsystems/NamingSystem-kzv-zahnarztnummer.xml 

### ISSUE THREAD

**Issue by BolteKZBV** [hl7germany/basisprofil-de-r4#52]
Statt der beschriebenen Lösung könnte ein 8-stelliges numerisches Feld, dass aus der Kombination aus KZV-Nummer (1. und 2. Stelle) und Abrechnungsnummer des Zahnarztes (3.-8. Stelle), bzw.  der Praxis im Falle von Berufsausübungsgemeinschaften besteht, eingeführt werden.
Dies entspricht der Festlegung der Zahnartznummer in der Anlage 14b des BMV-Z.

**Comment by lhitc** [comment]
Pre-Adoption, da in abgeleiteten Profilen benötigt.
