### ISSUE TITLE
address line extension mit Straße und Hausnummer

### ISSUE THREAD

**Issue by tliebscher** [hl7germany/basisprofil-de-r4#55]
Straße und Hausnummer zur Adresierung eines Gebäudes ist zwar ein verbreitetes Konzept in Deutschland, aber es gibt Gegenbeispiele, bei denen die Adresszeile das geeignetere generischere Konzept ist.

Das bekannteste Beispiel ist vermutlich das Stadtzentrum von Mannheim, bei denen nicht die Straßen sondern die Häuserblocks Bezeichner haben (hier Quadratebezeichnungen nach Buchstaben und Ziffern, bspw. O5, P6). Ein solches Quadrat hat 4 angrenzende Straßen, die zum Block gehörenden Häuser teilen sich aber die Blockbezeichnung. Zwei Häuser die sich an gegenüberliegenden Straßenseiten befinden, haben andere Blöcke und damit andere Bezeichnungen vor der Hausnummer (O5, 5 und P5, 5). Die gleiche Hausnummer kann dadurch zweimal in der gleichen Straße vorkommen.
Anderes seltenes Beispiel ist Hilgermissen in Niedersachsen, welches keine Straßennamen hat, sondern nur Hausnummern.

Würde O5 in Mannheim in der addres line extension als Straße behandelt werden?

**Comment by simoneOnFhir** [comment]
https://chat.fhir.org/#narrow/stream/179183-german-(d-a-ch)/topic/.5BBASIS.5D.20Issue.2355.3A.20Strasse.2FHausnummer

**Comment by alexzautke** [comment]
Klarstellung im aktuellen Implementation Guide: Address.line wird für die Zustell- oder Abholangabe verwendet. Hierzu würde laut DIN 5508 auch das genannte Konzept der Quadratebezeichnungen gehören. Siehe https://simplifier.net/guide/basisprofil-de-r4/Patient#Name
