### ISSUE TITLE
Code fehlt in https://simplifier.net/basisprofil-de-r4/vitalsignde_arterielle_sauerstoffsaettigung_pulsoximetrie

### ISSUE THREAD

**Issue by simoneOnFhir** [hl7germany/basisprofil-de-r4#591]
https://simplifier.net/basisprofil-de-r4/vitalsignde_arterielle_sauerstoffsaettigung_pulsoximetrie hat keinen vorgegebenen LOINC code. Sollte wahrscheinlich so wie in https://simplifier.net/medizininformatikinitiative-modul-intensivmedizin/sd_mii_icu_sauerstoffsaettigung_im_arteriellen_blut_durch_pulsoxymetrie im Slice loinc-fhir-core codiert werden...?

**Comment by simoneOnFhir** [comment]
Nope. Für 2708-6 gibt esbereits ein anderes Profil: https://simplifier.net/basisprofil-de-r4/vitalsignde_arterielle_sauerstoffsaettigung

**Comment by patrick-werner** [comment]
fixed by: https://github.com/hl7germany/basisprofil-de-r4/pull/600
