### ISSUE TITLE
IdentifierKvid10 kvid-2 Constraint

### ISSUE THREAD

**Issue by julsas** [hl7germany/basisprofil-de-r4#598]
https://github.com/hl7germany/basisprofil-de-r4/blob/2913ef5eeb983f9131a81744214ba37250f66591/resources/input/fsh/profiles/IdentifierKvid10.fsh#L9

Die Expression triggert nicht im Kontext Identifier.type.
```
($this.identifier.type.coding.exists(system='http://fhir.de/CodeSystem/identifier-type-de-basis' and code='GKV') or $this.identifier.type.coding.exists(system='http://fhir.de/CodeSystem/identifier-type-de-basis' and code='PKV')).not()
```

Sollte sein:
```
($this.coding.exists(system='http://fhir.de/CodeSystem/identifier-type-de-basis' and code='GKV') or $this.coding.exists(system='http://fhir.de/CodeSystem/identifier-type-de-basis' and code='PKV')).not()
```

**Comment by julsas** [comment]
Test case -> [Fhirpath Lab](https://fhirpath-lab.azurewebsites.net/FhirPath/?expression=%28%24this.coding.exists%28system%3D%27http%3A%2F%2Ffhir.de%2FCodeSystem%2Fidentifier-type-de-basis%27%20and%20code%3D%27GKV%27%29%20or%20%24this.coding.exists%28system%3D%27http%3A%2F%2Ffhir.de%2FCodeSystem%2Fidentifier-type-de-basis%27%20and%20code%3D%27PKV%27%29%29.not%28%29&engine=java%20%28HAPI%29&context=Patient.identifier.type&resourceJson=N4KABGBEBOCmDOB7ArtAxrAKgTwA60gC4oAFAQwBcBLWAOwsgBpwoqATO6gMxuiLADaLCKAhioFPAWKjxYyGkRsqtAOb8hcubK3iFS6VADSANQBaARgAMTYboiR42eBVgBbfpAAWFCrkIA9AFcXlTQAHQcAQDCBgDKzq5uAeycVDyw0AC0kvhZHFkARmTwVPCQdloAvsz2IpW6%20hyeJKa2dfJOLu6ePn6BwaERUbEcCd3JqfTpvDlS%20bBFJWUVHVUNEAC6DTUNjok9xN6%20-kEhYZGwAaVsAaoA1gBuAU-sWdbtcpDI8IaQiFweGgqGQADafPSPMHIP4AcQAnPCAKxWADMViRADYAOyrMTrLYgdZAA&terminologyserver=https%3A%2F%2Fsqlonfhir-r4.azurewebsites.net%2Ffhir)

**Comment by julsas** [comment]
> kvid-2: Als Type sollte der Code 'KVZ10' verwendet werden, die Codes 'GKV' und 'PKV' haben den Status 'retired'

Die Human description ist außerdem uneindeutig und unscharf. IdentifierKvid10 hat ein Pattern auf KVZ10, also MUSS KVZ10 verwendet werden.

**Comment by patrick-werner** [comment]
PR merged, ich lasse hier noch offen wegen der description
