### ISSUE TITLE
Coverage.type hat keinen Wert für "Sonstige Kostenträger"

### ISSUE THREAD

**Issue by simoneOnFhir** [hl7germany/basisprofil-de-r4#62]
Wurde von der KBV im Zuge der eAU hinzugefügt:
https://simplifier.net/EAU/KBVVSFORPayortype

Sollte in den Basisprofilen ergänzt werden....

**Comment by simoneOnFhir** [comment]
Betrifft: https://simplifier.net/Basisprofil-DE-R4/versicherungsart-de-basis

**Comment by simoneOnFhir** [comment]
und https://simplifier.net/basisprofil-de-r4/valueset-versicherungsartdebasis

**Comment by lhitc** [comment]
Das zweite genannte VS war ein inzwischen entferntes Duplikat
