### ISSUE TITLE
Alle Identifierprofile

### ISSUE THREAD

**Issue by mmreith** [hl7germany/basisprofil-de-r4#63]
Eigentlich sollte es kein Problem sein, ist es aber bei manchen Validatoren.

Beim Identifier.type gibt es ein Binding an identifier-type (extensible) http://hl7.org/fhir/r4/valueset-identifier-type.html

Da der genutzte Code dort nicht enthalten kommt es zu Validierungsfehlern.

Gruß Max

**Comment by alexzautke** [comment]
Der Java Validator gibt in diesem Fall, nach unserem Wissen nach, "nur" eine Warning aus. Dies resultiert daher, dass ein extensible-Binding nicht validiert werden kann. Dies ist lediglich ein Hinweis für die AnwenderIn, dass man den Code doppelt prüfen sollte. Für die Identifier Type Codes existiert jedoch innerhalb von http://hl7.org/fhir/ValueSet/identifier-type keine passenden Codes. Somit ist es korrekt weitere eigene Codes zu wählen.
