### ISSUE TITLE
Seitenlokalisation unter Bodysite

### ISSUE THREAD

**Issue by mmreith** [hl7germany/basisprofil-de-r4#64]
Es wurde ja schon mal in Zulip erwähnt, aber es wäre von unserer Seite aus sinnvoller, dass die Seitenlokalisation in Richtung http://fhir.de/StructureDefinition/CodingICD10GM wandert, da 

1. die Seitenlokalisation ein ICD Thema ist
2. die Bodysite mehr als nur R,L, Beidseitig ist

Wir würden das ICD Thema an der Stelle gerne zusammenhalten wollen und die Bodysite freihalten, um dort mit mglw. mit Sno...CT eine richtige Angabe der Körperstelle zu definieren.

Gruß Max

**Comment by simoneOnFhir** [comment]
https://chat.fhir.org/#narrow/stream/179183-german-(d-a-ch)/topic/.5BBASIS.5D.20Issue.2364.3A.20Seitenlokalisation

**Comment by alexzautke** [comment]
Invariante wurde hinzugefügt, dass die Seitenlokalisation nicht nur in der Extension sondern auch im Code enthalten ist.
