### ISSUE TITLE
Über diesen Leitfaden - Dead Links

### ISSUE THREAD

**Issue by abiernat-cerner** [hl7germany/basisprofil-de-r4#66]
Auf http://ig.fhir.de/basisprofile-de/stable/berdiesenLeitfaden.html im Abschnitt _Aufbau dieses Implementierungsleitfadens_ sind die Links defekt.

**Comment by simoneOnFhir** [comment]
Danke für den Hinweis, die entsprechenden Kapitel gibt es im aktuellen Leitfaden nicht mehr. Ich habe die Links entfernt.
