### ISSUE TITLE
Ergänzende Angaben Extension

### ISSUE THREAD

**Issue by mmreith** [hl7germany/basisprofil-de-r4#69]
Eine Extension für "ergänzende Angaben", die mindestens an einen Patient und einen Practitioner gehängt werden kann wäre sinnvoll. Die KBV möchte damit Angaben, wie z.B. "Patient wird schnell ohnmächtig" transportieren können.

Gruß Max Reith

**Comment by mmreith** [comment]
Ich ziehe den Antrag erstmal zurück...Wir werden erstmal kein Freitextbaustein an dieser Stelle verwenden.

**Comment by simoneOnFhir** [comment]
zurückgezogen
