### ISSUE TITLE
Coverage Erweiterungen

### ISSUE THREAD

**Issue by simoneOnFhir** [hl7germany/basisprofil-de-r4#74]
eingereicht von Bettina Lieske, SAP SE (bettina.lieske@sap.com)

Coverage
(http://ig.fhir.de/basisprofile-de-r4/0.9.2/Versicherungs-Informationen.html)
a) Selbstzahler:
• Es gibt diverse Fälle, in denen nicht der Patient als Selbstzahler, sondern andere Personen
oder Organisationen als Rechnungsempfänger fungierten. Hier ein paar Beispiele:
o Organtransplantation: Dort ist dann der aus Sicht des Organspenders der
Organempfänger (als Selbstzahler) der Rechnungsempfänger und wurde entsprechend
als VV im Fall des Organspenders hinterlegt.
o Konsile für externe Krankenhäuser (z.B. Einstellungstests mit anonymer Rechnung an
eine zentrale Hochschulstelle).
o Ausländische Patienten
• Zusätzlich gib es noch andere Kostenträger wie Bundeswehr, Polizei, Postbeamte /
Postangestellte, ... die alle ihre eigenen Regeln haben. Diese sind zwar alle „Selbstzahler“,
aber sollten nicht zusammengefasst werden, um nachfolgende Prozesse steuern zu können.
b) Ermächtigung
• In den Extensions zur Coverage sind so ziemlich alle Informationen, die auch in §301 Segment
INV übermittelt werden. Was uns fehlt is das „Vertragskennzeichen“, das bei ASV-Fällen die
ASV-Teamnummer enthält und bei Hochschulambulanzen die Ermächtigung (INV-10).
• Sollte dies nicht auch in der Coverage sein? Oder haben wir sie übersehen?

**Comment by simoneOnFhir** [comment]
Diskussion hier: https://chat.fhir.org/#narrow/stream/179316-german.2Fterminologien/topic/.5BBASIS.5D.20Issue.2374.3A.20weitere.20Kostentr.C3.A4ger

**Comment by simoneOnFhir** [comment]
..und hier: 
https://chat.fhir.org/#narrow/stream/179183-german-(d-a-ch)/topic/.5BBASIS.5D.20Issue.2374.3A.20Erm.C3.A4chtigungen

**Comment by alexzautke** [comment]
Duplikat von https://github.com/hl7germany/basisprofil-de-r4/issues/74 und https://github.com/hl7germany/basisprofil-de-r4/issues/73
