### ISSUE TITLE
Abbildung des Amtlicher Gemeindeschlüssel

### ISSUE THREAD

**Issue by alexzautke** [hl7germany/basisprofil-de-r4#88]
Für Forschungsdatensätzen mit Bezug auf regionale Auswertungen ist es teilweise sinnvoll nicht die PLZ zu verwenden (da Bezirks und teilweise Bundesland-übergreifend!) sondern den Amtlichen Gemeindeschlüssel. Vorschlag: Zum Address-Profil wird eine Extension auf Address.city hinzugefügt.

**Comment by alexzautke** [comment]
Siehe https://de.wikipedia.org/wiki/Amtlicher_Gemeindeschlüssel

**Comment by simoneOnFhir** [comment]
ist erledigt, oder @alexzautke ?

**Comment by alexzautke** [comment]
Abschnitt zum IG wurde hinzugefügt. Extension wurde erstellt.
