### ISSUE TITLE
Anpassung der Benennungen der ICD-10 Coding Extensions

### ISSUE THREAD

**Issue by alexzautke** [hl7germany/basisprofil-de-r4#91]
https://simplifier.net/basisprofil-de-r4/conditiondeicd10

Die Benennungen der ICD-10 Coding Extension sollten an die Begrifflichkeiten des DIMDI angepasst werden:

HauptKreuzCode => ~~Ätiologiecode~~ Primaercode
Sterncode => Manifestationscode

**Comment by simoneOnFhir** [comment]
ist erledigt, oder?

**Comment by alexzautke** [comment]
Umbenennung wurde bereits erledigt.
